### ISSUE TITLE
Nuget package exists?

### ISSUE THREAD

**Issue by OmidID** [CefNet/CefNet#1]
Does any package exist for Avalonia on Nuget?

**Comment by vmas** [comment]
https://www.nuget.org/packages/CefNet.Avalonia/

**Comment by OmidID** [comment]
@vmas Thanks,
I found out this project (https://gitlab.com/joaompneves/cefglue) it's really similar to what you did.
Is it the same or you have another approach?

**Comment by vmas** [comment]
That project has a slightly different approach.

**Comment by OmidID** [comment]
@vmas I added your project to awesome projects of Avalonia
https://github.com/AvaloniaCommunity/awesome-avalonia
