### ISSUE TITLE
Error "TryShutdown" in cefnet.avalonia90.6 is not supported

### ISSUE THREAD

**Issue by lijianxin520** [CefNet/CefNet#112]
Hello, I am using the CefNet.Avalonia component and have encountered an error.
![image](https://user-images.githubusercontent.com/47262889/184619663-37cbb188-6c43-40e6-b2c9-543eb6bb34eb.png)
Below is my project configuration information
![image](https://user-images.githubusercontent.com/47262889/184619753-1328bf88-dd09-482b-ba59-f3704db44e85.png)

**Comment by vmas** [comment]
Update CefNet to 100+ or downgrade Avalonia to 0.10.3.
