### ISSUE TITLE
Help,The program crashes when the mouse prompt of title attribute moves fast

### ISSUE THREAD

**Issue by xionger3015** [CefNet/CefNet#125]
The program crashes when the mouse prompt of title attribute moves fast.
![image](https://user-images.githubusercontent.com/119378518/205201303-9c8dd702-c58c-4731-91de-4770b18a080b.png)
![be73aa97adc7dcc7866a85cdd80ad7a](https://user-images.githubusercontent.com/119378518/205199393-577e7e72-22f4-4dca-b17a-4a8968533b39.png)
![9de71ae2b10e92479116eb069a03833](https://user-images.githubusercontent.com/119378518/205199437-a464ba8c-089f-4ea4-b0af-badbb7f02faa.png)
![1669948071790](https://user-images.githubusercontent.com/119378518/205201144-ad7cb099-d973-4e72-87b3-81122303a0e7.jpg)
![image](https://user-images.githubusercontent.com/119378518/205199593-bf509881-e3a9-40e3-8eed-c5e6d26e6fb9.png)

**Comment by xionger3015** [comment]
The sudo operation of the terminal can avoid

**Comment by haizzh** [comment]
您好，问你一下。使用sudo命令后提示未安装dotnet环境。麒麟系统怎么给管理员权限安装dotnet

**Comment by xionger3015** [comment]
可以看看这个教程：https://www.bbsmax.com/A/amd0Gpek5g/





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CefNet/CefNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月23日(星期四) 下午2:40
***@***.***&gt;;
抄送:&nbsp;" ***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [CefNet/CefNet] Help,The program crashes when the mouse prompt of title attribute moves fast (Issue #125)





 
您好，问你一下。使用sudo命令后提示未安装dotnet环境。麒麟系统怎么给管理员权限安装dotnet
