### ISSUE TITLE
How convert byte[] or Stream to IntPtr?

### ISSUE THREAD

**Issue by neostfox** [CefNet/CefNet#14]
`protected override bool Read(IntPtr dataOut, int bytesToRead, ref int bytesRead, CefResourceReadCallback callback)
		{
			byte[] data = Encoding.UTF8.GetBytes("hello world");
			bytesRead  = data.Length;
			Marshal.Copy(data, 0, dataOut, data.Length);
			callback.Continue(bytesRead);
                         return true;
		}
`
I try like this but it response nothing?

**Comment by vmas** [comment]
See https://github.com/CefNet/CefNet/commit/b0b517cdef6c4c0ddcbaf870217f50e65f7570a2#diff-8cf8e8bfe9e38b057bafb10982873352

**Comment by neostfox** [comment]
Thank you I‘ll try it
