### ISSUE TITLE
Can you help me how to use cefnet with Nuget.my demo did not run

### ISSUE THREAD

**Issue by wuzlai** [CefNet/CefNet#17]
Hi,Does anyone knows how to use cefnet with Vs Nuget . 
I have finished a demo,but it does not work.
There is a problem:
System.InvalidOperationException:“Failed to create browser instance.”
![image](https://user-images.githubusercontent.com/7692353/89246264-55db3580-d63d-11ea-963d-d698b9dc6a48.png)

I just want to know how to use cefnet. Can anyone help me? If so, I can send the code to you

**Comment by vmas** [comment]
Can you provide an example of your code that reproduces the issue?

**Comment by wuzlai** [comment]
> Can you provide an example of your code that reproduces the issue?



> Can you provide an example of your code that reproduces the issue

> Can you provide an example of your code that reproduces the issue?



> Can you provide an example of your code that reproduces the issue?

Hi,I upload my demo , https://github.com/wuzlai/test
Note,i use cef_binary_83.5.0+gbf03589+chromium-83.0.4103.106_windows64. I hope you can take a look at it when you're free. I really need this ,thank you~

**Comment by vmas** [comment]
There is no [CEF init code](https://github.com/CefNet/CefNet/blob/master/AvaloniaApp/App.xaml.cs#L37) in your example.

**Comment by wuzlai** [comment]
> [CEF init code](https://github.com/CefNet/CefNet/blob/master/AvaloniaApp/App.xaml.cs#L37) in your example.

Thanks,i use Nuget. how  show i do  about CEF init code ??  can you give me a demo or example .thank you~

**Comment by vmas** [comment]
Look at the initialization code in the [App.xaml.cs](https://github.com/CefNet/CefNet/blob/master/AvaloniaApp/App.xaml.cs#L37) file. You need to create an instance of CefNetApplication (CefAppImpl in example) and call CefNetApplication::Initialize() passing the path to the CEF binaries and your CefSettings.

**Comment by wuzlai** [comment]
> Look at the initialization code in the [App.xaml.cs](https://github.com/CefNet/CefNet/blob/master/AvaloniaApp/App.xaml.cs#L37) file. You need to create an instance of CefNetApplication (CefAppImpl in example) and call CefNetApplication::Initialize() passing the path to the CEF binaries and your CefSettings.

Hi,you are right. i have run the demo succuessfully, but now i have another problem,How do I use this control to display HMTL, for example, if I pass an HTML tag to CEFNet. Will it display the HTML.Could you tell me .thanks
![image](https://user-images.githubusercontent.com/7692353/89481295-04ac7c80-d7ca-11ea-84a7-face7d2f68f9.png)
![image](https://user-images.githubusercontent.com/7692353/89481512-7ab0e380-d7ca-11ea-9c0b-e1e3673e0cf7.png)

**Comment by vmas** [comment]
Just navigate to file:///C:/Users/Wuzl/Desktop/a.html
Another way: load `data:text/html,<html><body>123456</body></html>`.
If you want to download HTML with a specific URL take a look at this commit: b0b517c

**Comment by wuzlai** [comment]
> Just navigate to file:///C:/Users/Wuzl/Desktop/a.html
> Another way: load `data:text/html,<html><body>123456</body></html>`.
> If you want to download HTML with a specific URL take a look at this commit: [b0b517c](https://github.com/CefNet/CefNet/commit/b0b517cdef6c4c0ddcbaf870217f50e65f7570a2)

Thank you for your reply. You may have misunderstood my question.
I mean to display HTML strings in cefnet.in a word.
string strhtml="<html><body>123456</body></html>";
??????
Now .i want to know how to use Cefnet to show the 'strhtml'.
Render my HTML tags out of the interface

**Comment by vmas** [comment]
You can convert your string to HTML using WebUtility.HtmlEncode() and load the resulting string as I wrote above.

**Comment by wuzlai** [comment]
> You can convert your string to HTML using WebUtility.HtmlEncode() and load the resulting string as I wrote above.
> Or load as `data:text/plain,<html>...</html>`

In my case, my HMTL data is dynamic. I received different HMTL data each time, and then showed it to CEFnet,and i do not create html file.

About your 'Another way: load data:text/html,<html><body>123456</body></html>.'   I'm a little confused.i try it .but failed.
I think There's something wrong with me. Can you tell me how I should write this process

![image](https://user-images.githubusercontent.com/7692353/89500293-16a31500-d7f4-11ea-9a32-274b252b7ada.png)

**Comment by wuzlai** [comment]
> > You can convert your string to HTML using WebUtility.HtmlEncode() and load the resulting string as I wrote above.
> > Or load as `data:text/plain,<html>...</html>`
> 
> In my case, my HMTL data is dynamic. I received different HMTL data each time, and then showed it to CEFnet,and i do not create html file.
> 
> About your 'Another way: load data:text/html,123456.' I'm a little confused.i try it .but failed.
> I think There's something wrong with me. Can you tell me how I should write this process
> 
> ![image](https://user-images.githubusercontent.com/7692353/89500293-16a31500-d7f4-11ea-9a32-274b252b7ada.png)

![image](https://user-images.githubusercontent.com/7692353/89500386-405c3c00-d7f4-11ea-986a-87af9aebe36c.png)

**Comment by vmas** [comment]
```
string strHtml = "data:text/plain,<html><body>123456</body></html>";
SelectedView?.Navigate(strHtml);
```
or
```
string src = "<html><body>123456</body></html>";
string strHtml = "data:text/html," + WebUtility.HtmlEncode(src);
SelectedView?.Navigate(strHtml);
```

**Comment by wuzlai** [comment]
> ```
> string strHtml = "data:text/plain,<html><body>123456</body></html>";
> SelectedView?.Navigate(strHtml);
> ```
> 
> or
> 
> ```
> string src = "<html><body>123456</body></html>";
> string strHtml = "data:text/html," + WebUtility.HtmlEncode(src);
> SelectedView?.Navigate(strHtml);
> ```
i try it ,but both failed. A little sad.
![image](https://user-images.githubusercontent.com/7692353/89502569-caf26a80-d7f7-11ea-8d22-617294bf73a5.png)

![image](https://user-images.githubusercontent.com/7692353/89502507-b0b88c80-d7f7-11ea-9bd3-c1ae15ebf110.png)

**Comment by vmas** [comment]
I don't understand what you want.

**Comment by wuzlai** [comment]
> I don't understand what you want.
I mean I send HTML to CEF. The browser can parse the HTML tag and display it.
example.
![image](https://user-images.githubusercontent.com/7692353/89504529-be234600-d7fa-11ea-8d5a-eaa57a19ab86.png)
![image](https://user-images.githubusercontent.com/7692353/89504627-e90d9a00-d7fa-11ea-8f04-96a96fbae499.png)

**Comment by vmas** [comment]
```
string strHtml = "<!DOCTYPE html><html><head><title>666</title></head><body>123456</body></html>";
SelectedView?.Navigate("data:text/html;charset=utf-8," + strHtml);
```

**Comment by wuzlai** [comment]
> string strHtml = "<!DOCTYPE html><html><head><title>666</title></head><body>123456</body></html>";

Thank you very much, suceessfully,Tears of excitement

![image](https://user-images.githubusercontent.com/7692353/89506180-515d7b00-d7fd-11ea-882a-3f44136dcbf4.png)
