### ISSUE TITLE
Does CefNet  Support MacOS,Help me

### ISSUE THREAD

**Issue by wuzlai** [CefNet/CefNet#19]
Hello,
I'm using CefNet with Avalonia. On windows and linux platform everything goes well.
now I'm trying to make it working on MacOS but without success. and i already use cef files in Contents
I have try 2 ways.one is publish files directly.another is to packages.but they does not work.
![image](https://user-images.githubusercontent.com/7692353/89767028-b67ddd00-db2b-11ea-92a5-38c26693aff9.png)
![image](https://user-images.githubusercontent.com/7692353/89767139-e5944e80-db2b-11ea-8e5f-580acf064daa.png)
![image](https://user-images.githubusercontent.com/7692353/89767221-0a88c180-db2c-11ea-8c37-550b4f89a4d3.png)
Does anyone knows it ,thank youk
the project url:https://github.com/wuzlai/test

**Comment by vmas** [comment]
Your application (app bundle) must have a specific layout:

```
application.app/
    Contents/
        Frameworks/
            Chromium Embedded Framework.framework/
                Chromium Embedded Framework <= main application library
                Resources/
                    cef.pak, devtools_resources.pak, ... <= non-localized resources and strings
                    icudtl.dat <= unicode support data
                    natives_blob.bin, snapshot_blob.bin <= V8 initial snapshot
                    en.lproj/, ... <= locale-specific resources and strings
            application Helper.app/
                Contents/
                    Info.plist
                    MacOS/
                        application Helper <= helper executable
                    Pkginfo
            application Helper (GPU).app/
                Contents/
                    Info.plist
                    MacOS/ <= symbolic link to 'application Helper.app/.../MacOS' allowed here
                        application Helper (GPU) <= helper executable
                    Pkginfo
            application Helper (Plugin).app/
                Contents/
                    Info.plist
                    MacOS/ <= symbolic link to 'application Helper.app/.../MacOS' allowed here
                        application Helper (Plugin) <= helper executable
                    Pkginfo
            application Helper (Renderer).app/
                Contents/
                    Info.plist
                    MacOS/ <= symbolic link to 'application Helper.app/.../MacOS' allowed here
                        application Helper (Renderer) <= helper executable
                    Pkginfo
        Info.plist
        MacOS/ <= symbolic link to 'application Helper.app/.../MacOS' allowed here
            application <= application executable
        Pkginfo
        Resources/
            application.icns, ... <= application resources
```
See [build-osx-app.sh](https://github.com/CefNet/CefNet/blob/master/build-osx-app.sh) for an example.

**Comment by wuzlai** [comment]
> Your application (app bundle) must have a specific layout:
> 
> ```
> application.app/
>     Contents/
>         Frameworks/
>             Chromium Embedded Framework.framework/
>                 Chromium Embedded Framework <= main application library
>                 Resources/
>                     cef.pak, devtools_resources.pak, ... <= non-localized resources and strings
>                     icudtl.dat <= unicode support data
>                     natives_blob.bin, snapshot_blob.bin <= V8 initial snapshot
>                     en.lproj/, ... <= locale-specific resources and strings
>             application Helper.app/
>                 Contents/
>                     Info.plist
>                     MacOS/
>                         application Helper <= helper executable
>                     Pkginfo
>             application Helper (GPU).app/
>                 Contents/
>                     Info.plist
>                     MacOS/ <= symbolic link to 'application Helper.app/.../MacOS' allowed here
>                         application Helper (GPU) <= helper executable
>                     Pkginfo
>             application Helper (Plugin).app/
>                 Contents/
>                     Info.plist
>                     MacOS/ <= symbolic link to 'application Helper.app/.../MacOS' allowed here
>                         application Helper (Plugin) <= helper executable
>                     Pkginfo
>             application Helper (Renderer).app/
>                 Contents/
>                     Info.plist
>                     MacOS/ <= symbolic link to 'application Helper.app/.../MacOS' allowed here
>                         application Helper (Renderer) <= helper executable
>                     Pkginfo
>         Info.plist
>         MacOS/ <= symbolic link to 'application Helper.app/.../MacOS' allowed here
>             application <= application executable
>         Pkginfo
>         Resources/
>             application.icns, ... <= application resources
> ```
> 
> See [build-osx-app.sh](https://github.com/CefNet/CefNet/blob/master/build-osx-app.sh) for an example.
> More info: https://bitbucket.org/chromiumembedded/cef/wiki/GeneralUsage.md#markdown-header-application-layout

thank you ,the .app strcucture, i do not have some files. indeed. can you tell me where to find these. please see the picture
![image](https://user-images.githubusercontent.com/7692353/89772512-b2a28880-db34-11ea-8782-aff9eb249833.png)

**Comment by wuzlai** [comment]
> Your application (app bundle) must have a specific layout:
> 
> ```
> application.app/
>     Contents/
>         Frameworks/
>             Chromium Embedded Framework.framework/
>                 Chromium Embedded Framework <= main application library
>                 Resources/
>                     cef.pak, devtools_resources.pak, ... <= non-localized resources and strings
>                     icudtl.dat <= unicode support data
>                     natives_blob.bin, snapshot_blob.bin <= V8 initial snapshot
>                     en.lproj/, ... <= locale-specific resources and strings
>             application Helper.app/
>                 Contents/
>                     Info.plist
>                     MacOS/
>                         application Helper <= helper executable
>                     Pkginfo
>             application Helper (GPU).app/
>                 Contents/
>                     Info.plist
>                     MacOS/ <= symbolic link to 'application Helper.app/.../MacOS' allowed here
>                         application Helper (GPU) <= helper executable
>                     Pkginfo
>             application Helper (Plugin).app/
>                 Contents/
>                     Info.plist
>                     MacOS/ <= symbolic link to 'application Helper.app/.../MacOS' allowed here
>                         application Helper (Plugin) <= helper executable
>                     Pkginfo
>             application Helper (Renderer).app/
>                 Contents/
>                     Info.plist
>                     MacOS/ <= symbolic link to 'application Helper.app/.../MacOS' allowed here
>                         application Helper (Renderer) <= helper executable
>                     Pkginfo
>         Info.plist
>         MacOS/ <= symbolic link to 'application Helper.app/.../MacOS' allowed here
>             application <= application executable
>         Pkginfo
>         Resources/
>             application.icns, ... <= application resources
> ```
> 
> See [build-osx-app.sh](https://github.com/CefNet/CefNet/blob/master/build-osx-app.sh) for an example.
> More info: https://bitbucket.org/chromiumembedded/cef/wiki/GeneralUsage.md#markdown-header-application-layout

I download the sample Application. Should I just copy these files to my software package
![image](https://user-images.githubusercontent.com/7692353/89773251-25603380-db36-11ea-87e0-612e64e17bea.png)

**Comment by vmas** [comment]
These are the directories with your application files. You shouldn't copy files from the sample app.

**Comment by wuzlai** [comment]
> These are the directories with your application files. You shouldn't copy files from the sample app.
> 
> `application Helper`, `application Helper (Renderer)`, etc. is your application's binary.

Oh ,these files need me to do ,please tell me how to make these files?  

I see your ssh files.i only find 'copy' .do not see produce 

![image](https://user-images.githubusercontent.com/7692353/89778491-344be380-db40-11ea-96b2-e68bbfab4fc0.png)

**Comment by vmas** [comment]
This file is produced with `dotnet publish`: https://github.com/CefNet/CefNet/blob/83f73f3267df72ad62fc33af3c6645c8a77bbd08/build-osx-app.sh#L66
And later copied with different names.

**Comment by wuzlai** [comment]
> This file is produced with `dotnet publish`:
> 
> https://github.com/CefNet/CefNet/blob/83f73f3267df72ad62fc33af3c6645c8a77bbd08/build-osx-app.sh#L66
> 
> 
> And later copied with different names.

Thank  you ,i will try it as soon as possible.

**Comment by wuzlai** [comment]
> This file is produced with `dotnet publish`:
> 
> https://github.com/CefNet/CefNet/blob/83f73f3267df72ad62fc33af3c6645c8a77bbd08/build-osx-app.sh#L66
> 
> 
> And later copied with different names.

Hi,i use your ssh file to do in mac os .A software package was successfully produced.but the .app does not work.
i have try it many times.can you give me a demo?? or can you try me code  .the project url:https://github.com/wuzlai/test
and i use cef 'cef_binary_83.5.0+gbf03589+chromium-83.0.4103.106_macosx64'
I'd appreciate it if you could help me

![image](https://user-images.githubusercontent.com/7692353/89981736-f7e6c780-dca6-11ea-8398-9a9a3c290401.png)
![image](https://user-images.githubusercontent.com/7692353/89981745-fcab7b80-dca6-11ea-8e5f-ae423b185e10.png)

![image](https://user-images.githubusercontent.com/7692353/89981754-02a15c80-dca7-11ea-9581-a61efc85fa1e.png)



create_app_structure() {
    APPNAME=$1
    APPDIR="$APPNAME.app/Contents"
    APPICONS="/Users/wuzhenglai/Downloads/mac/avaloniaApp.icns"

    if [ ! -d "$APPDIR" ]; then
        echo "creating app structure $APPDIR"

        mkdir -vp "$APPDIR"/{Resources,Frameworks}
        cp -v "$APPICONS" "$APPDIR/Resources/$APPNAME.icns"
    fi
}

emit_plist() {
    PLIST_APPNAME=$1
    PLIST_PATH="$2/Info.plist"
    
    if [ "$3" ]; then
        LSUIELEMENT="false"
    else
        LSUIELEMENT="true"
    fi
    
    if [ ! -f "$PLIST_PATH" ]; then
        echo "emiting $PLIST_PATH"
        cat <<EOF > "$PLIST_PATH"
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleExecutable</key>
    <string>$PLIST_APPNAME</string>
    <key>CFBundleGetInfoString</key>
    <string>$PLIST_APPNAME</string>
    <key>CFBundleIconFile</key>
    <string>$PLIST_APPNAME</string>
    <key>CFBundleName</key>
    <string>$PLIST_APPNAME</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleSignature</key>
    <string>????</string>
    <key>LSUIElement</key>
    <string>$LSUIELEMENT</string>
</dict>
</plist>
EOF
    fi
}


BINARYNAME="AvaloniaApp"
CONFIGURATION="Debug"
NETTARGET="netcoreapp3.1"
CEFZIP="cef_binary_84.3.8%2Bgc8a556f%2Bchromium-84.0.4147.105_macosx64_minimal.tar.bz2"
TARGET="bin"


if [ ! -d "$TARGET" ]; then
    mkdir "$TARGET"
fi

#cd "$TARGET"

echo "Building CefNet Avalonia demo..."
dotnet publish AvaloniaApp.csproj -c "$CONFIGURATION" -r osx-x64 -f "$NETTARGET" -o "publish" --self-contained

CEFBINARIES="../cef"
CEFFRAMEWORK_DIR="$(find $CEFBINARIES -name "Release")"



APPNAME="$BINARYNAME"
APPDIR="$APPNAME.app/Contents"

rm -rf "$APPDIR"

create_app_structure "$APPNAME"
emit_plist "$APPNAME" "$APPDIR" true

cp -R "$CEFFRAMEWORK_DIR/Chromium Embedded Framework.framework" "$APPDIR/Frameworks/"

cd "$APPDIR/Frameworks"

APPNAME="$BINARYNAME Helper"
APPDIR="$APPNAME.app/Contents"
create_app_structure "$APPNAME"
emit_plist "$APPNAME" "$APPDIR"
cp -R "../../../publish/" "$APPDIR/MacOS"
ln -s "Frameworks/$APPDIR/MacOS" "../MacOS"
chmod +x "$APPDIR/MacOS/$BINARYNAME"
cp "$APPDIR/MacOS/$BINARYNAME" "$APPDIR/MacOS/$APPNAME"
chmod +x "$APPDIR/MacOS/$APPNAME"

APPNAME="$BINARYNAME Helper (GPU)"
APPDIR="$APPNAME.app/Contents"
mkdir -pv "$APPDIR"
emit_plist "$APPNAME" "$APPDIR"
ln -s "../../$BINARYNAME Helper.app/Contents/MacOS" "$APPDIR/MacOS"
cp "$APPDIR/MacOS/$BINARYNAME" "$APPDIR/MacOS/$APPNAME"
chmod +x "$APPDIR/MacOS/$APPNAME"

APPNAME="$BINARYNAME Helper (Plugin)"
APPDIR="$APPNAME.app/Contents"
mkdir -pv "$APPDIR"
emit_plist "$APPNAME" "$APPDIR"
ln -s "../../$BINARYNAME Helper.app/Contents/MacOS" "$APPDIR/MacOS"
cp "$APPDIR/MacOS/$BINARYNAME" "$APPDIR/MacOS/$APPNAME"
chmod +x "$APPDIR/MacOS/$APPNAME"


APPNAME="$BINARYNAME Helper (Renderer)"
APPDIR="$APPNAME.app/Contents"
mkdir -pv "$APPDIR"
emit_plist "$APPNAME" "$APPDIR"
ln -s "../../$BINARYNAME Helper.app/Contents/MacOS" "$APPDIR/MacOS"
cp "$APPDIR/MacOS/$BINARYNAME" "$APPDIR/MacOS/$APPNAME"
chmod +x "$APPDIR/MacOS/$APPNAME"

**Comment by vmas** [comment]
You should change this line to the compatible CEF version:
`CEFZIP="cef_binary_84.3.8%2Bgc8a556f%2Bchromium-84.0.4147.105_macosx64_minimal.tar.bz2"`
See also issue #22 

Working example:
[cef-84_4-example.zip](https://github.com/CefNet/CefNet/files/5063718/cef-84_4-example.zip)

**Comment by wuzlai** [comment]
> You should change this line to the compatible CEF version:
> `CEFZIP="cef_binary_84.3.8%2Bgc8a556f%2Bchromium-84.0.4147.105_macosx64_minimal.tar.bz2"`
> See also issue #22
> 
> Working example:
> [cef-84_4-example.zip](https://github.com/CefNet/CefNet/files/5063718/cef-84_4-example.zip)

thank you very much.it works.

**Comment by wuzlai** [comment]
> You should change this line to the compatible CEF version:
> `CEFZIP="cef_binary_84.3.8%2Bgc8a556f%2Bchromium-84.0.4147.105_macosx64_minimal.tar.bz2"`
> See also issue #22
> 
> Working example:
> [cef-84_4-example.zip](https://github.com/CefNet/CefNet/files/5063718/cef-84_4-example.zip)

Hello, excuse me again, these referenced packages cef_binary are too large, I would like to ask if there is any possibility of streamlining.
Or I can get rid of some files that I don't really use. 
It's basically a folder Release,it is too large.I already try Standard Distribution and Minimal Distribution.but all the same
I now make the software package, there are more than 100 MB

![image](https://user-images.githubusercontent.com/7692353/90089969-5bc7c980-dd55-11ea-87bd-e03a4f08053c.png)

![image](https://user-images.githubusercontent.com/7692353/90090002-75691100-dd55-11ea-8a80-4bc5484db7d5.png)

**Comment by vmas** [comment]
Only 2 folders are required: Release and Resources. The *.lib files can be deleted.

**Comment by wuzlai** [comment]
> Only 2 folders are required: Release and Resources. The *.lib files can be deleted.

 Only 2 folders are required: Release and Resources,but the2 floders are too larger indedd.
I choose 3 files.windows,linux,mac.
in windows .i delete the *.lib ,everything goes well.The volume has been reduced by about 50MB
![image](https://user-images.githubusercontent.com/7692353/90105650-d7873d80-dd78-11ea-8c99-f415b27c4938.png)

in linux.can you tell me which type file could be deleted 
![image](https://user-images.githubusercontent.com/7692353/90106052-701dbd80-dd79-11ea-8739-3245070501d7.png)

in mac.can you tell me which type file could be deleted 
![image](https://user-images.githubusercontent.com/7692353/90106115-8c215f00-dd79-11ea-8fa8-590d258db2a0.png)

A few more questions. Thank you very much

**Comment by vmas** [comment]
You'd better ask about this on the CEF forum: https://magpcss.org/ceforum/

**Comment by wuzlai** [comment]
> 
Ok ,thank you very much.
