### ISSUE TITLE
Raspberry pi4 

### ISSUE THREAD

**Issue by zhangjacob123** [CefNet/CefNet#2]
Hi

I use raspberry pi4 to run AvaloniaApp show as blow error .but run at win10 is normal.

[0225/122816.022161:WARNING:gpu_process_host.cc(1213)] The GPU process has crashed 9 time(s)
[0225/122816.022329:FATAL:gpu_data_manager_impl_private.cc(990)] The display compositor is frequently crashing. Goodbye.

**Comment by vmas** [comment]
What OS and and architecture?
Does the problem reproduce with the cefclient or cefsimple sample application at the same version?

Try these flags: --no-zygote --no-sandbox --disable-gpu --disable-gpu-compositing --in-process-gpu

**Comment by zhangjacob123** [comment]
> Does the problem reproduce with the cefclient or cefsimple sample application at the same version?
OS:Raspbian
cef version:cef_binary_79.1.38+gecefb59+chromium-79.0.3945.130_linuxarm_minimal.tar.bz2

I have try this flags, but still unable

**Comment by zhangjacob123** [comment]
**```
Unknown option: --type=gpu-process
Unknown option: --field-trial-handle=14886124742158904649,14274594811461871877,131072
Unknown option: --disable-features=MimeHandlerViewInCrossProcessFrame
Unknown option: --no-sandbox
Unknown option: --locales-dir-path=/home/pi/Code/app/cef/Resources/locales
Unknown option: --log-file=/home/pi/dotnet/debug.log
Unknown option: --log-severity=warning
Unknown option: --resources-dir-path=/home/pi/Code/app/cef/Resources
Unknown option: --lang=en-US
Unknown option: --gpu-preferences=KAAAAAAAAAAgAAAgAAAAAAAAYAAAAAAAEAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAA
Unknown option: --use-gl=disabled
Unknown option: --log-file=/home/pi/dotnet/debug.log
Unknown option: --service-request-channel-token=12712940634237078965
[0225/163741.212602:WARNING:gpu_process_host.cc(1213)] The GPU process has crashed 9 time(s)
[0225/163741.212914:FATAL:gpu_data_manager_impl_private.cc(990)] The display compositor is frequently crashing. Goodbye.
```**
AvaloniaApp can see the UI when it is started, but it will report an error after a few seconds.

**Comment by vmas** [comment]
It looks like the dotnet subprocess is starting instead of AvaloniaApp. Are you running ```./AvaloniaApp``` or ```dotnet AvaloniaApp.dll```?

**Comment by zhangjacob123** [comment]
run  dotnet AvaloniaApp.dll

**Comment by vmas** [comment]
I run ```./AvaloniaApp```

**Comment by zhangjacob123** [comment]
> I run `./AvaloniaApp`

yes, I try run `./AvaloniaApp under Linux is normal . Thanks.
