### ISSUE TITLE
Upgrde  to avalonia 0.10.0 Preview5, something went wrong.

### ISSUE THREAD

**Issue by wuzlai** [CefNet/CefNet#24]
Hi.
  @vmas . @vmas i need your help.  i use your code run successfunlly in avalonia 0.9.12 . the demo url is https://github.com/CefNet/CefNet/files/5063718/cef-84_4-example.zip

But when I upgraded to 0.10.0 Preview5, something went wrong.
![image](https://user-images.githubusercontent.com/7692353/92542883-994c4380-f27c-11ea-89f5-09fee303f657.png)

If avalonia has been upgraded, cefnet also needs to be modified accordingly. I noticed that the AddHandler interface had changed, and I tried to run the source code for Cefnet, but it failed. I hope to get your help to check whether the cefnet under the new version (Avalonia 0.10.0) is running properly
![image](https://user-images.githubusercontent.com/7692353/92542955-c4cf2e00-f27c-11ea-885f-781d273b4bde.png)

**Comment by bsglinux16** [comment]
> Hi.
> @vmas . @vmas i need your help. i use your code run successfunlly in avalonia 0.9.12 . the demo url is https://github.com/CefNet/CefNet/files/5063718/cef-84_4-example.zip
> 
> But when I upgraded to 0.10.0 Preview5, something went wrong.
> ![image](https://user-images.githubusercontent.com/7692353/92542883-994c4380-f27c-11ea-89f5-09fee303f657.png)
> 
> If avalonia has been upgraded, cefnet also needs to be modified accordingly. I noticed that the AddHandler interface had changed, and I tried to run the source code for Cefnet, but it failed. I hope to get your help to check whether the cefnet under the new version (Avalonia 0.10.0) is running properly
> ![image](https://user-images.githubusercontent.com/7692353/92542955-c4cf2e00-f27c-11ea-885f-781d273b4bde.png)

yes not working on 0.10 preview 5

**Comment by wuzlai** [comment]
> 0.10.0 Preview5, somethin

yeah,but vmas has modified, A version 0.10 branch has been opened, but it is still in the bug collection phase. Maybe later. Update nuget.
the url is https://github.com/vmas/CefNet/tree/avalonia-0.10
you can use the souuce code in your project.At least that's what I'm doing so far

**Comment by bsglinux16** [comment]
> > 0.10.0 Preview5, somethin
> 
> yeah,but vmas has modified, A version 0.10 branch has been opened, but it is still in the bug collection phase. Maybe later. Update nuget.
> the url is https://github.com/vmas/CefNet/tree/avalonia-0.10
> you can use the souuce code in your project.At least that's what I'm doing so far

good thanks

**Comment by wuzlai** [comment]
> > > 0.10.0 Preview5, somethin
> > 
> > 
> > yeah,but vmas has modified, A version 0.10 branch has been opened, but it is still in the bug collection phase. Maybe later. Update nuget.
> > the url is https://github.com/vmas/CefNet/tree/avalonia-0.10
> > you can use the souuce code in your project.At least that's what I'm doing so far
> 
> good thanks

You're welcome. Help each other.
