### ISSUE TITLE
How do I manually upgrade the version of Avalonia referenced in the Cefnet source code

### ISSUE THREAD

**Issue by wuzlai** [CefNet/CefNet#25]
Hi
  @vmas  excuse you, Ask some questions. I download your code branch(https://github.com/vmas/CefNet/tree/avalonia-0.10). It will run successfully. But I have a question I'd like to ask you. How did you upgrade the version of the Cefnet package referenced by avalonia, say from 0.9.12 to 0.10.0? I have tried to upgrade or downgrade myself, but have failed.
![image](https://user-images.githubusercontent.com/7692353/93055018-dbbab980-f69c-11ea-88fd-54a9348a0f4b.png)

**Comment by vmas** [comment]
1. Right click on the project and click "Edit CefNet.Avalonia.csproj". This will open up CSPROJ file for editing.
2. Replace the Avalonia package version with the one you want. Save changes.
3. Run command line (cmd.exe) and execute `dotnet restore` in the project directory.
4. Right click on the project and click "Clean".
5. Build project.

**Comment by wuzlai** [comment]
> 1. Right click on the project and click "Edit CefNet.Avalonia.csproj". This will open up CSPROJ file for editing.
> 2. Replace the Avalonia package version with the one you want. Save changes.
> 3. Run command line (cmd.exe) and execute `dotnet restore` in the project directory.
> 4. Right click on the project and click "Clean".
> 5. Build project.

thank you I have learned to upgrade the source branch manually. As an additional trivia, Cefnet CustomWebView will run successfully in the Window page. When I use CustomWebView on the UserControl page, I get an error telling the browser that the object is empty. I went through the cefnet source code and found that it only allowed the Window page to call functionality like CustomWebView. Then, what I need now is to call CustomWebView on the UserConrol page to display HTML information instead of the Window page. I have not thought of the method for the moment. Do you have any good Suggestions

CEFView.axxaml is ok,it is Window page
![image](https://user-images.githubusercontent.com/7692353/93189247-7e923700-f774-11ea-8ff8-70d883b2949e.png)
![image](https://user-images.githubusercontent.com/7692353/93189346-9c5f9c00-f774-11ea-9975-b39f8733a8d5.png)

CEFControl.axaml run failed,it is usercontrol page
![image](https://user-images.githubusercontent.com/7692353/93189441-b8633d80-f774-11ea-96e5-25e96cea6e50.png)
![image](https://user-images.githubusercontent.com/7692353/93189458-bdc08800-f774-11ea-9268-1c4760940e0b.png)

**Comment by vmas** [comment]
You shouldn't call CEF methods (SendDragOverEvent) in the constructor. At this point, the browser has not yet been created.

**Comment by wuzlai** [comment]
> You shouldn't call CEF methods (SendDragOverEvent) in the constructor. At this point, the browser has not yet been created.

thank you  ,you are right .i got it.
I am glad to tell you that I have integrated Cefnet into my project. However, I suddenly found that I met two difficulties. If you could spare some time to reply me, I would be very grateful to you. The first problem is that I need to get the web page address that the current browser is visiting. For example, if My Cefnet is visiting Google, I can get the page address www.google.hk in the program. The second question is how to get the content of the page in the browser. Such as some text displayed on the page and so on. I have a lot of questions, and the information I have found so far is limited. I hope you can reply when you are free. Thank you.

**Comment by vmas** [comment]
The WebView::BeforeBrowse event is called before the frame is navigated to a new document. You can cancel navigation by setting BeforeBrowseArgs.Cancel = true.

**Comment by wuzlai** [comment]
> BeforeBrowse

thank you .i will try
