### ISSUE TITLE
Not Working!

### ISSUE THREAD

**Issue by bsglinux16** [CefNet/CefNet#26]
cefnet library does not work on avalonia

Even though I added the cef binary files, it doesn't work

it just stays there without any errors.

**Comment by vmas** [comment]
What version of the product are you using? On what operating system? What architecture x86 or x64? Probably haven't copied icudtl.dat to the cef/Release directory.

**Comment by bsglinux16** [comment]
I am using cefnet version 84.4

I added the ready library from nuget to my project and downloaded the 84.4 compiled version of cef and placed it with the compiled files.

system architecture x64

**Comment by vmas** [comment]
Have you copied the icudtl.dat file to the Release folder? Are you using Linux? On Linux, the application must be run with the --no-zygote --no-sandbox.

**Comment by bsglinux16** [comment]
![image](https://user-images.githubusercontent.com/35398147/93668769-7f3e0c80-fa97-11ea-877c-b6e71decf78e.png)

I copy the cef files you see in the picture into the release folder, but there is no reaction.
does not open sites

**Comment by vmas** [comment]
Have you written the [CEF initialization code](https://github.com/CefNet/CefNet/blob/master/AvaloniaApp/App.xaml.cs)? Does [the sample app](https://github.com/CefNet/CefNet/tree/master/AvaloniaApp) work for you?

**Comment by bsglinux16** [comment]
> Have you written the [CEF initialization code](https://github.com/CefNet/CefNet/blob/master/AvaloniaApp/App.xaml.cs)? Does [the sample app](https://github.com/CefNet/CefNet/tree/master/AvaloniaApp) work for you?

Project Cannot Build my Visual Studio build failing

Added Cef Init Code And Get Failed To Create Browser Instance Error

**Comment by bsglinux16** [comment]
> > Have you written the [CEF initialization code](https://github.com/CefNet/CefNet/blob/master/AvaloniaApp/App.xaml.cs)? Does [the sample app](https://github.com/CefNet/CefNet/tree/master/AvaloniaApp) work for you?
> 
> Project Cannot Build my Visual Studio build failing so cannot tested sample app
> 
> Added Cef Init Code And Get Failed To Create Browser Instance Error

**Comment by vmas** [comment]
Check the debug.log file for errors.

**Comment by bsglinux16** [comment]
debug.log blank

![image](https://user-images.githubusercontent.com/35398147/93670490-66882380-faa4-11ea-8997-e213f47ba268.png)
errors getting

![image](https://user-images.githubusercontent.com/35398147/93670496-76076c80-faa4-11ea-823e-4b4045e3708f.png)
code

**Comment by vmas** [comment]
Why are you using Dispatcher.UIThread.InvokeAsync here?

**Comment by bsglinux16** [comment]
![image](https://user-images.githubusercontent.com/35398147/93670605-4311a880-faa5-11ea-8891-20254bfee687.png)
It gives this error but I was able to fix it using dispatcher.

**Comment by bsglinux16** [comment]
I looked through the Project Codes and I Noticed That WebView Is Generating Its Own Init Code.

I Get This Error When I Add the Initialize Command or Not.

**Comment by bsglinux16** [comment]
I am Tried Cefnet 84.2 and 84.3 But Not Working

**Comment by vmas** [comment]
Initialization must be done on the UI thread. If the UI thread is not STA then mark the Program::Main() method with the STAThreadAttribute.

**Comment by bsglinux16** [comment]
> Initialization must be done on the UI thread. If the UI thread is not STA then mark the Program::Main() method with the STAThreadAttribute.

I am doing the Initialization in MainWindow.Axaml.Cs.

**Comment by bsglinux16** [comment]
![image](https://user-images.githubusercontent.com/35398147/93670767-73a61200-faa6-11ea-8df2-c549610be773.png)

**Comment by vmas** [comment]
Move the initialization code to Program::Main.

**Comment by bsglinux16** [comment]
> Move the initialization code to Program::Main.

Program.Cs ?

**Comment by vmas** [comment]
yes

**Comment by bsglinux16** [comment]
![image](https://user-images.githubusercontent.com/35398147/93670810-c97aba00-faa6-11ea-9610-88e6798762c4.png)
before or after

**Comment by vmas** [comment]
Before buildavaloniaapp

**Comment by vmas** [comment]
And add `settings.MultiThreadedMessageLoop = true;`

**Comment by bsglinux16** [comment]
> Before buildavaloniaapp

okey please wait trying

**Comment by bsglinux16** [comment]
cef version 84.4.1 
true ?

**Comment by vmas** [comment]
what cefnet version?

**Comment by bsglinux16** [comment]
![image](https://user-images.githubusercontent.com/35398147/93670910-62a9d080-faa7-11ea-9e00-3dd7e790b30c.png)
latest

**Comment by vmas** [comment]
Then 84.4.1

**Comment by bsglinux16** [comment]
> Then 84.4.1

okey downloaded already

**Comment by bsglinux16** [comment]
![image](https://user-images.githubusercontent.com/35398147/93670965-d055fc80-faa7-11ea-94c6-2b94a2e1b117.png)
worked bro thanks

But!
![image](https://user-images.githubusercontent.com/35398147/93670970-d946ce00-faa7-11ea-8b4a-480b79f044e7.png)
I am getting this error after 10-15 seconds could not figure out where it originated.

**Comment by bsglinux16** [comment]
> I don't know. Possible exception in Avalonia.Skia.dll.
> You also need to add app.Shutdown() at the end of the Main() method for the CEF to shutdown correctly.

add cef.shutdown buildavaloniapp after ? or mainwindow_closing event (x button)

**Comment by vmas** [comment]
after buildavaloniapp

**Comment by bsglinux16** [comment]
> after buildavaloniapp

Added CefShutdown

Interestingly, the error time was up to 40 seconds.

And I Have No Problem If I Open The Program Without Debugger

I think Debugger Catches This Error But If You Have Used Try Catch, It Doesn't Cause Problem.

**Comment by bsglinux16** [comment]
Since the problem will always give an error, it will prevent me from seeing the errors of other codes.

What can we do?

Error Info: [Visual] Exception in render loop: "System.NullReferenceException: Object reference not set to an instance of an object.
    at Avalonia.Skia.FramebufferRenderTarget.CreateDrawingContext (IVisualBrushRenderer visualBrushRenderer)
    at Avalonia.Rendering.DeferredRenderer.EnsureDrawingContext (IDrawingContextImpl & context)
    at Avalonia.Rendering.DeferredRenderer.UpdateRenderLayersAndConsumeSceneIfNeeded (IDrawingContextImpl & context, Boolean recursiveCall)
    at Avalonia.Rendering.DeferredRenderer.Render (Boolean forceComposite)
    at Avalonia.Rendering.RenderLoop.TimerTick (TimeSpan time) "(Avalonia.Rendering.RenderLoop # 12547953)
An exception of type 'Avalonia.Skia.dll' occurred on System.NullReferenceException

**Comment by vmas** [comment]
Ask here: https://gitter.im/AvaloniaUI/Avalonia

**Comment by bsglinux16** [comment]
> Ask here: https://gitter.im/AvaloniaUI/Avalonia

Okey

Final Question Does CefNet Work the Same on Linux and Mac?

**Comment by vmas** [comment]
On Mac, the application must use --external-message-pump.
On Linux, the application must be run with --no-sandbox --no-zygote
See AvaloniaApp and issue #19 for details.

**Comment by bsglinux16** [comment]
> On Mac, the application must use --external-message-pump.
> On Linux, the application must be run with --no-sandbox --no-zygote
> See AvaloniaApp and issue #19 for details.

Thanks really good


I think the error is caused by the attached context menu. If you want a look at the codes.
https://github.com/AvaloniaUI/Avalonia/issues/2513

**Comment by bsglinux16** [comment]
How Can I Add Command Line to Cef?

**Comment by vmas** [comment]
https://github.com/CefNet/CefNet/blob/master/WinFormsCoreApp/CefAppImpl.cs

**Comment by bsglinux16** [comment]
> https://github.com/CefNet/CefNet/blob/master/WinFormsCoreApp/CefAppImpl.cs

connected event but not accept beforechildprocessstartargs
use default eventargs

**Comment by bsglinux16** [comment]
sorry i looked wrong

CefNetApplication

does not contain such a function or event

**Comment by bsglinux16** [comment]
Issues List


- [ ] Update CefNet Latest Cef Version

- [ ] Fix WebView Crash Skia Renderer

- [ ] cefnet does not have command line attachments by default.

**Comment by vmas** [comment]
> sorry i looked wrong
> 
> CefNetApplication
> 
> does not contain such a function or event
> 
> ![image](https://user-images.githubusercontent.com/35398147/93686110-c8ed1e00-fabc-11ea-90ca-430ac49c38bc.png)

This is protected method.

**Comment by bsglinux16** [comment]
> > sorry i looked wrong
> > CefNetApplication
> > does not contain such a function or event
> > ![image](https://user-images.githubusercontent.com/35398147/93686110-c8ed1e00-fabc-11ea-90ca-430ac49c38bc.png)
> 
> This is protected method.

why don't you include this in the library

**Comment by vmas** [comment]
You need to create a class inherited from CefNetApplication, then the OnBeforeCommandLineProcessing method will be available to you for overloading.

**Comment by bsglinux16** [comment]
> You need to create a class inherited from CefNetApplication, then the OnBeforeCommandLineProcessing method will be available to you for overloading.

I Already Added By Looking From The File.

But I Think It Would Be Nice If You Include It In The Library As An Event.

Both Have Problems To Fix.

I Wrote on Gitter for the Crash Problem.

**Comment by vmas** [comment]
Does a NullReferenceException occur when you try to open the context menu?

**Comment by bsglinux16** [comment]
> Does a NullReferenceException occur when you try to open the context menu?

No
It happens when I don't do anything
I guess contextmenu is not relevant

https://github.com/AvaloniaUI/Avalonia/issues/3410

They wrote that they were shrinking the window, but when I delete Webview, it does not fail.

**Comment by wuzlai** [comment]
Hello, it's good to see that other people are using Cefnet. I've got a problem. See if you've got one. Do you know how to scale cefnet's browser window? I defined the value of ZoomLevel, but it didn't work. @bsglinux16

**Comment by vmas** [comment]
> Since the problem will always give an error, it will prevent me from seeing the errors of other codes.
> 
> What can we do?
> 
> **Error Info**: [Visual] Exception in render loop: "System.NullReferenceException: Object reference not set to an instance of an object.
> at Avalonia.Skia.FramebufferRenderTarget.CreateDrawingContext (IVisualBrushRenderer visualBrushRenderer)
> at Avalonia.Rendering.DeferredRenderer.EnsureDrawingContext (IDrawingContextImpl & context)
> at Avalonia.Rendering.DeferredRenderer.UpdateRenderLayersAndConsumeSceneIfNeeded (IDrawingContextImpl & context, Boolean recursiveCall)
> at Avalonia.Rendering.DeferredRenderer.Render (Boolean forceComposite)
> at Avalonia.Rendering.RenderLoop.TimerTick (TimeSpan time) "(Avalonia.Rendering.RenderLoop # 12547953)
> An exception of type 'Avalonia.Skia.dll' occurred on System.NullReferenceException

Potential workaround: `WebView.ToolTip = null;`

**Comment by bsglinux16** [comment]
> Hello, it's good to see that other people are using Cefnet. I've got a problem. See if you've got one. Do you know how to scale cefnet's browser window? I defined the value of ZoomLevel, but it didn't work. @bsglinux16

Isn't this about avalonia?
I guess the cef has no zoom.

**Comment by bsglinux16** [comment]
> > Since the problem will always give an error, it will prevent me from seeing the errors of other codes.
> > What can we do?
> > **Error Info**: [Visual] Exception in render loop: "System.NullReferenceException: Object reference not set to an instance of an object.
> > at Avalonia.Skia.FramebufferRenderTarget.CreateDrawingContext (IVisualBrushRenderer visualBrushRenderer)
> > at Avalonia.Rendering.DeferredRenderer.EnsureDrawingContext (IDrawingContextImpl & context)
> > at Avalonia.Rendering.DeferredRenderer.UpdateRenderLayersAndConsumeSceneIfNeeded (IDrawingContextImpl & context, Boolean recursiveCall)
> > at Avalonia.Rendering.DeferredRenderer.Render (Boolean forceComposite)
> > at Avalonia.Rendering.RenderLoop.TimerTick (TimeSpan time) "(Avalonia.Rendering.RenderLoop # 12547953)
> > An exception of type 'Avalonia.Skia.dll' occurred on System.NullReferenceException
> 
> Potential workaround: `WebView.ToolTip = null;`

Wow I think the Error Fixed.
Why was Tooltip causing this error?

**Comment by wuzlai** [comment]
> > Hello, it's good to see that other people are using Cefnet. I've got a problem. See if you've got one. Do you know how to scale cefnet's browser window? I defined the value of ZoomLevel, but it didn't work. @bsglinux16
> 
> Isn't this about avalonia?
> I guess the cef has no zoom.

it is about avalonia.but i find ZoomLevel in source code of cefnet..maybe i could ask @vmas ,Excuse you, Do you know how to scale cefnet's browser window? I defined the value of ZoomLevel, but it didn't work.

**Comment by vmas** [comment]
This is the CEF feature. It works the same in Google Chrome. Changing zoom level for a domain changes it only in windows that load urls for that domain. Each zoom level increases the zoom by ~20%. More details:
https://magpcss.org/ceforum/viewtopic.php?f=6&t=11491

**Comment by wuzlai** [comment]
> This is the CEF feature. It works the same in Google Chrome. Changing zoom level for a domain changes it only in windows that load urls for that domain. Each zoom level increases the zoom by ~20%. More details:
> https://magpcss.org/ceforum/viewtopic.php?f=6&t=11491

Hello, I have looked carefully, but I still don't understand. According to the reference of the forum(There is a method on the browser called SetZoomLevel. This takes a double. I know that 0.0 means 100%; positive values are greater than 100% and negative ones are less), I set positive and negative Numbers respectively, but I can't see the effect of browser zooming. I am a little desperate, please guide me, thank you

![image](https://user-images.githubusercontent.com/7692353/93872023-258d4a80-fd02-11ea-83c9-e14b899b12ed.png)

**Comment by vmas** [comment]
The ZoomLevel only applies to the current web page. For example, it can be set in the Navigated event.

**Comment by bsglinux16** [comment]
> ZoomLevel yalnızca mevcut web sayfası için geçerlidir. Örneğin, Navigated olayında ayarlanabilir.

true

zoomlevel = chrome ctrl + mouse scroll

**Comment by bsglinux16** [comment]
@vmas 
https://github.com/AvaloniaUI/Avalonia/issues/4715

Can you add what you know about crashes to this issue?

**Comment by wuzlai** [comment]
> The ZoomLevel only applies to the current web page. For example, it can be set in the Navigated event.

thank you very much.

**Comment by wuzlai** [comment]
> > ZoomLevel yalnızca mevcut web sayfası için geçerlidir. Örneğin, Navigated olayında ayarlanabilir.
> 
> true
> 
> zoomlevel = chrome ctrl + mouse scroll

thanks.i do it

**Comment by bsglinux16** [comment]
> > > ZoomLevel yalnızca mevcut web sayfası için geçerlidir. Örneğin, Navigated olayında ayarlanabilir.
> > 
> > 
> > true
> > zoomlevel = chrome ctrl + mouse scroll
> 
> thanks.i do it

You're welcome

I am Closing issue
Moved Bugs and Issues #27
