### ISSUE TITLE
Hi,I found an interesting thing

### ISSUE THREAD

**Issue by wuzlai** [CefNet/CefNet#29]
Hi everyone, I found a strange thing. When I render HTML with CEF. Found that the browser does not recognize the hexadecimal color in the style. I ended up using the Google browser and found the same thing. Here are my comparison pictures, do you know what this is about?

![image](https://user-images.githubusercontent.com/7692353/94220456-9196cb00-ff1b-11ea-933f-c48a5b2f66a7.png)
![image](https://user-images.githubusercontent.com/7692353/94220463-978cac00-ff1b-11ea-876d-a240e036ad1d.png)

**Comment by vmas** [comment]
Replace # with %23.

**Comment by wuzlai** [comment]
> 用％23替换＃。



> Replace # with %23.

Thank you. Solved my big problem.

**Comment by wuzlai** [comment]
> Replace # with %23.

Thank you. Solved my big problem.
