### ISSUE TITLE
About packaging scripts build-osx-app.sh

### ISSUE THREAD

**Issue by wuzlai** [CefNet/CefNet#30]
Hi,i use the ssh scripts(build-osx-app.sh) to package,but it does not work. 
I guess some tools, such as ASM, may not have been installed. But I have found a lot of materials and have not solved them. Do you know how to solve them? I this is directly download the new version of the project, the address is https://github.com/vmas/CefNet/tree/avalonia-0.10. @vmas I hope you can help me out when you are free. Thank you very much.
In addition, I also download the program at https://github.com/CefNet/CefNet. Same question as him.

![image](https://user-images.githubusercontent.com/7692353/95642287-27188a00-0ada-11eb-8277-40b4354d6019.png)
![image](https://user-images.githubusercontent.com/7692353/95642298-34357900-0ada-11eb-9df5-e3022a2f8220.png)

**Comment by vmas** [comment]
You need to install DotAsm Tools:
`dotnet tool install -g DotAsm`

You will also need this patch: https://github.com/CefNet/CefNet/commit/b04dc83

**Comment by wuzlai** [comment]
> You need to install DotAsm Tools:
> `dotnet tool install -g DotAsm`
> 
> You will also need this patch: [b04dc83](https://github.com/CefNet/CefNet/commit/b04dc83)

thank you very much.I've made it
