### ISSUE TITLE
how to getsource (load url or file )

### ISSUE THREAD

**Issue by zhenggr520** [CefNet/CefNet#31]
@vmas
Hi, i use webview load a local html file, and then enter text in the input tag, how to get the input text or the html source?
thank you!

**Comment by vmas** [comment]
```
public static async Task<string> GetInputValueAsync(CefFrame frame, CancellationToken cancellationToken)
{
	dynamic scriptableObject = await frame.GetScriptableObjectAsync(cancellationToken).ConfigureAwait(false);
	string s = scriptableObject.window.document.querySelector("input").value;
	return s;
}
```
On UI thread:
```
string value = await GetInputValueAsync(webView.GetMainFrame(), CancellationToken.None);
```

**Comment by zhenggr520** [comment]
> ```
> public static async Task<string> GetInputValueAsync(CefFrame frame, CancellationToken cancellationToken)
> {
> 	dynamic scriptableObject = await frame.GetScriptableObjectAsync(cancellationToken).ConfigureAwait(false);
> 	string s = scriptableObject.window.document.querySelector("input").value;
> 	return s;
> }
> ```
> 
> On UI thread:
> 
> ```
> string value = await GetInputValueAsync(webView.GetMainFrame(), CancellationToken.None);
> ```

thank you~it works
