### ISSUE TITLE
I find a bug in cefnet about pop up window

### ISSUE THREAD

**Issue by wuzlai** [CefNet/CefNet#32]
I met a very unexpected situation, debugging a day have not found a way. I am a little anxious and anxious. Out of desperation, I hope to get help from @vmas . If you have time to look at my code, thank you very much. the project url is https://github.com/wuzlai/ZZApp

I used Avalonia to make a page that popped up, read the HTML file and displayed it.
This is a very simple feature, I developed under Windows, the project published, produced three versions, Windows, MAC OS, Centos. I tested each version separately. Finding software running under Windows and Centos is fine, but running under MAC OS is abnormal and always reports an error. I used the log to locate the point where the program made an exception, indicating that the object was empty. I'm confused. Why is It that Windows and Centos are fine and mac os has a problem, same set of code 

The operation of windows is as follows, what I want is that the pop-up box can be opened normally and display the content.
![image](https://user-images.githubusercontent.com/7692353/95847802-c01bff00-0d7f-11eb-8c58-55e263079c38.png)

The operation of mac os  is as follows, when i clicked the "Click Me" ，The program is abnormal。
![image](https://user-images.githubusercontent.com/7692353/95848753-0aea4680-0d81-11eb-9891-3572e2be2743.png)

my main code as follws:
`using Avalonia;
using Avalonia.Controls;
using Avalonia.Markup.Xaml;
using CefNet.Avalonia;
using System;
using System.IO;
using System.Threading;

namespace ZZApp.Views
{
    public class UserAgreementView : Window
    {
        public UserAgreementView()
        {
            this.InitializeComponent();

        }
        bool isInit = false;
        WebView webView;
        private void InitializeComponent()
        {
            AvaloniaXamlLoader.Load(this);
            webView = this.FindControl<WebView>("webView");
            this.Opened += UserAgreementView_Opened;
        }

        private void UserAgreementView_Opened(object sender, EventArgs e)
        {
            Thread.Sleep(100);
            if (!isInit)
            {
                Thread.Sleep(100);
                isInit = true;
                LoadFile();
            }
        }

       

        private void LoadFile()
        {
            string path = AppDomain.CurrentDomain.BaseDirectory;
            string filePath = Path.Combine(path,"UserAgreement_zh-cn.html");
           
            string content = string.Empty;
            using (StreamReader reader = new StreamReader(filePath))
            {
                content = reader.ReadToEnd();
            }
           
            webView.Navigate("data:text/html;charset=utf-8," + content);
          
        }
    }
}
`

So far, my Apple packaging is no problem. The interface can be displayed normally, but the pop-up box shows that Google Chrome is abnormal. This situation only occurs under mac os, other systems are normal. I suspect that the Apple system has limitations? Does cefnet need to pay attention to macos? Such as initialization, @vmas . please take a look at some time, thank you .my project address is https://github.com/wuzlai/ZZApp

**Comment by bsglinux16** [comment]
need more information for a bug.

**Comment by wuzlai** [comment]
> need more information for a bug.

Hi，I've screenshot the error message.
![image](https://user-images.githubusercontent.com/7692353/96668377-9f5e3580-138d-11eb-81a9-682014195346.png)

![image](https://user-images.githubusercontent.com/7692353/96668272-61611180-138d-11eb-9561-a399c1ca7848.png)

I hope you can give me some hints. Thank you.

**Comment by bsglinux16** [comment]
> > need more information for a bug.
> 
> Hi，I've screenshot the error message.
> ![image](https://user-images.githubusercontent.com/7692353/96668377-9f5e3580-138d-11eb-81a9-682014195346.png)
> 
> ![image](https://user-images.githubusercontent.com/7692353/96668272-61611180-138d-11eb-9561-a399c1ca7848.png)
> 
> I hope you can give me some hints. Thank you.



Can You Submit Crash Information via paste.ubuntu.com? and you can add try catch to the Click Event of the button and get the error code in c #, because We will also need the error code c #

**Comment by vmas** [comment]
Stack trace:
```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at CefNet.Avalonia.WebView.Navigate(String url) in /Users/osx/work/wuzlai/ZZApp/CefNet/WebView.CommonImplementation.cs:line 758
   at ZZApp.Views.UserAgreementView.LoadFile() in /Users/osx/work/wuzlai/ZZApp/ZZApp/Views/UserAgreementView.axaml.cs:line 51
   at ZZApp.Views.UserAgreementView.UserAgreementView_Opened(Object sender, EventArgs e) in /Users/osx/work/wuzlai/ZZApp/ZZApp/Views/UserAgreementView.axaml.cs:line 34
   at Avalonia.Controls.TopLevel.OnOpened(EventArgs e)
   at Avalonia.Controls.Window.ShowCore(Window parent)
   at Avalonia.Controls.Window.Show()
   at ZZApp.ViewModels.MainWindowViewModel.btnClick() in /Users/osx/work/wuzlai/ZZApp/ZZApp/ViewModels/MainWindowViewModel.cs:line 16
   at Avalonia.Data.Converters.MethodToCommandConverter.Execute(Object parameter)
   at Avalonia.Controls.Button.OnClick()
   at Avalonia.Controls.Button.OnPointerReleased(PointerReleasedEventArgs e)
   at Avalonia.Input.InputElement.<>c.<.cctor>b__26_9(InputElement x, PointerReleasedEventArgs e)
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs:line 146
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e)
   at Avalonia.Interactivity.EventRoute.RaiseEvent(IInteractive source, RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e)
   at Avalonia.Input.MouseDevice.MouseUp(IMouseDevice device, UInt64 timestamp, IInputRoot root, Point p, PointerPointProperties props, KeyModifiers inputModifiers)
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawPointerEventArgs e)
   at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e)
   at Avalonia.Native.WindowBaseImpl.RawMouseEvent(AvnRawMouseEventType type, UInt32 timeStamp, AvnInputModifiers modifiers, AvnPoint point, AvnVector delta)
   at Avalonia.Native.Interop.IAvnWindowBaseEventsShadow.IAvnWindowBaseEventsVtbl.RawMouseEvent(IntPtr thisObject, Int32 param0, UInt32 param1, Int32 param2, AvnPoint param3, AvnVector param4)
--- End of stack trace from previous location where exception was thrown ---
   at Avalonia.Native.PlatformThreadingInterface.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at ZZApp.Program.Main(String[] args) in /Users/osx/work/wuzlai/ZZApp/ZZApp/Program.cs:line 15
Abort trap: 6
```

**Comment by vmas** [comment]
The browser has not yet been created when WebView.Navigate() is called.

**Comment by wuzlai** [comment]
> The browser has not yet been created when WebView.Navigate() is called.

What you said is right. The browser object is empty and then calls Navigate is abnormal. The point is That I don't know how to avoid this, the best I can do is add thread hibernation and take the Opend event. This works well for Windows and Linux, but when you run it under MacOS, you get a hint that the object is not initialized. So post it and see if you have any better Suggestions? Cefnet.avalonia will always occasionally get this error :" Object reference not set to an instance of an Object."



![Uploading image.png…]()

**Comment by wuzlai** [comment]
> > > need more information for a bug.
> > 
> > 
> > Hi，I've screenshot the error message.
> > ![image](https://user-images.githubusercontent.com/7692353/96668377-9f5e3580-138d-11eb-81a9-682014195346.png)
> > ![image](https://user-images.githubusercontent.com/7692353/96668272-61611180-138d-11eb-9561-a399c1ca7848.png)
> > I hope you can give me some hints. Thank you.
> 
> Can You Submit Crash Information via paste.ubuntu.com ? and you can add try catch to the Click Event of the button and get the error code in c #, because We will also need the error code c #

thank you, the error code is System.NullReferenceException: Object reference not set to an instance of an object.
The browser object is empty and then calls Navigate is abnormal. The point is That I don't know how to avoid this, the best I can do is add thread hibernation and take the Opend event. This works well for Windows and Linux, but when you run it under MacOS, you get a hint that the object is not initialized. So post it and see if you have any better Suggestions? Cefnet.avalonia will always occasionally get this error :" Object reference not set to an instance of an Object."

![Uploading image.png…]()

**Comment by vmas** [comment]
You can use the WebView.BrowserCreated event.

**Comment by wuzlai** [comment]
> You can use the WebView.BrowserCreated event.

Thanks, I used BrowserCreated event, also added exception capture, and logging, and so on, now the situation is Windows normal display page, everything is normal. But MAC OS can open forms normally, but can't display web pages, and I can't catch exceptions. The process is right.

![image](https://user-images.githubusercontent.com/7692353/96855265-12030a00-148f-11eb-8219-cde7ac2f9dcb.png)

![image](https://user-images.githubusercontent.com/7692353/96855294-19c2ae80-148f-11eb-8ae9-1091eb13932b.png)
![image](https://user-images.githubusercontent.com/7692353/96855314-1fb88f80-148f-11eb-9254-ca067c61b801.png)

**Comment by wuzlai** [comment]
I wonder if there was a problem initializing CEF on MAC OS

**Comment by vmas** [comment]
Try
`await Avalonia.Threading.Dispatcher.UIThread.InvokeAsync(() => webView.Navigate("http://google.com"));`

**Comment by bsglinux16** [comment]
> I wonder if there was a problem initializing CEF on MAC OS

If You Using Mac on Virtual Machine
CEF may start late due to performance issues

**Comment by wuzlai** [comment]
> Try
> `await Avalonia.Threading.Dispatcher.UIThread.InvokeAsync(() => webView.Navigate("http://google.com"));`

thank you very much,accorging to your tips.i run it successfully,Here is my key code.The main cause of the problem is that the CEF is not fully initialized.
![image](https://user-images.githubusercontent.com/7692353/96978888-71295300-1551-11eb-8044-1fd7959b3600.png)
I have also compared the performance of the real machine with that of the virtual machine. If the real machine runs smoothly, the virtual machine may be much slower. If the project is small, this speed difference can be ignored. At least that's how the demo cases and projects I've written look. Demo opens web pages faster, while cEF initializations for projects are slower. For the root cause, I do not know for the time being, feedback first.

**Comment by wuzlai** [comment]
> > I wonder if there was a problem initializing CEF on MAC OS
> 
> If You Using Mac on Virtual Machine
> CEF may start late due to performance issues

Thank you. You're quite right. I did use a virtual machine, and when I used a real machine to debug it, I found that it was much faster, and the virtual machine was likely to stay blank, waiting to be displayed. The real machine will display normally in about 2 or 3 seconds.

**Comment by wuzlai** [comment]
Thank you very much for your help, my project can continue to develop, thank you
@vmas  @bsglinux16

**Comment by bsglinux16** [comment]
> > > I wonder if there was a problem initializing CEF on MAC OS
> > 
> > 
> > If You Using Mac on Virtual Machine
> > CEF may start late due to performance issues
> 
> Thank you. You're quite right. I did use a virtual machine, and when I used a real machine to debug it, I found that it was much faster, and the virtual machine was likely to stay blank, waiting to be displayed. The real machine will display normally in about 2 or 3 seconds.

Instead of the browsercreated event, there should be an event like browser loaded. cef should be calling this event when fully loaded.

**Comment by bsglinux16** [comment]
> Thank you very much for your help, my project can continue to develop, thank you
> @vmas @bsglinux16

you're welcome

**Comment by vmas** [comment]
> I have also compared the performance of the real machine with that of the virtual machine. If the real machine runs smoothly, the virtual machine may be much slower. If the project is small, this speed difference can be ignored. At least that's how the demo cases and projects I've written look. Demo opens web pages faster, while cEF initializations for projects are slower. For the root cause, I do not know for the time being, feedback first.

Perhaps you could use the WebView.InitialUrl property in InitializeComponent() instead WebView.Navigate().

**Comment by bsglinux16** [comment]
> > I have also compared the performance of the real machine with that of the virtual machine. If the real machine runs smoothly, the virtual machine may be much slower. If the project is small, this speed difference can be ignored. At least that's how the demo cases and projects I've written look. Demo opens web pages faster, while cEF initializations for projects are slower. For the root cause, I do not know for the time being, feedback first.
> 
> Perhaps you could use the WebView.InitialUrl property in InitializeComponent() instead WebView.Navigate().

True

**Comment by wuzlai** [comment]
> > I have also compared the performance of the real machine with that of the virtual machine. If the real machine runs smoothly, the virtual machine may be much slower. If the project is small, this speed difference can be ignored. At least that's how the demo cases and projects I've written look. Demo opens web pages faster, while cEF initializations for projects are slower. For the root cause, I do not know for the time being, feedback first.
> 
> Perhaps you could use the WebView.InitialUrl property in InitializeComponent() instead WebView.Navigate().

thank you,i will try it.
