### ISSUE TITLE
enable javascript in linux

### ISSUE THREAD

**Issue by zhenggr520** [CefNet/CefNet#34]
@vmas
hi,I use cefnet and load a html file with some javascript in linux,the file is loaded but the javascript code can not be run,even if I add the following code.how do I enable javascript in linux? thank you!
commandLine.AppendSwitch("enable-javascript");

**Comment by vmas** [comment]
JavaScript is enabled by default. There may be a security issue. Have you tried the `disable-web-security` flag?

**Comment by zhenggr520** [comment]
Just tried it as you said, but it still doesn't work

**Comment by zhenggr520** [comment]
@vmas
hi, I found that as long as the "#" exists in the file, even if it is annotated code, it will cause the execution of js to fail. Is there any solution?

like the simple code below.
In fact, my files will be more complicated and there will be a lot of "#".

<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>
    <textarea id="content"></textarea>
</body>
   <script type="text/javascript">
        //var color="#";
        document.getElementById("content").innerHTML="123";
    </script>
</html>

**Comment by vmas** [comment]
How do you load the file?

**Comment by zhenggr520** [comment]
webView.Navigate(fileName);

**Comment by vmas** [comment]
I have not been able to reproduce this error. Anyway, this is probably a bug in CEF / Chromium.

**Comment by zhenggr520** [comment]
ok,thank you!
