### ISSUE TITLE
Compile cefnet project error using VisualStudio under MacOS

### ISSUE THREAD

**Issue by wuzlai** [CefNet/CefNet#39]
One question, I ran the CEF. Avalonia demo on my MAC. Found an error in Visual Studio compilation. However, I use the command line tool dotnet Publish to publish directly without exception.

Below is a screenshot of the exception message prompted
![image](https://user-images.githubusercontent.com/7692353/101715846-251d7800-3ad7-11eb-866b-68052ea02599.png)

The following is the exception message that is prompted

/Users/mesign/Downloads/SDApp/CefNet/obj/Debug/netstandard2.0/CefNet.il (46263, 39): Error: irrecoverable syntax error (CefNet)

/Users/mesign/Downloads/SDApp/CefNet/CefNet.csproj(5,5): Error MSB3073: 命令“mono "/Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/4.5/ilasm.exe" /nologo /quiet /output:"/Users/mesign/Downloads/SDApp/CefNet/obj/Debug/netstandard2.0/CefNet.dll" -alignment=512 -dll -pdb -resource:"/Users/mesign/Downloads/SDApp/CefNet/obj/Debug/netstandard2.0/CefNet.res.obj" "/Users/mesign/Downloads/SDApp/CefNet/obj/Debug/netstandard2.0/CefNet.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Managed/MSIL/CefAccessibilityHandler.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Managed/MSIL/CefApp.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Managed/MSIL/CefAudioHandler.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Managed/MSIL/CefBrowserProcessHandler.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Managed/MSIL/CefClient.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Managed/MSIL/CefContextMenuHandler.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Managed/MSIL/CefCookieAccessFilter.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Managed/MSIL/CefCookieVisitor.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Managed/MSIL/CefDeleteCookiesCallback.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Managed/MSIL/CefDevToolsMessageObserver.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Managed/MSIL/CefDialogHandler.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Managed/MSIL/CefDisplayHandler.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Managed/MSIL/CefDOMVisitor.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Managed/MSIL/CefDownloadHandler.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Managed/MSIL/CefDownloadImageCallback.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Managed/MSIL/CefDragHandler.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Managed/MSIL/CefEndTracingCallback.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Managed/MSIL/CefExtensionHandler.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Managed/MSIL/CefFindHandler.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Managed/MSIL/CefFocusHandler.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Managed/MSIL/CefJSDialogHandler.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Managed/MSIL/CefKeyboardHandler.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Managed/MSIL/CefLifeSpanHandler.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Managed/MSIL/CefLoadHandler.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Managed/MSIL/CefMediaObserver.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Managed/MSIL/CefMediaRouteCreateCallback.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Managed/MSIL/CefMediaSinkDeviceInfoCallback.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Managed/MSIL/CefMenuModelDelegate.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Managed/MSIL/CefNavigationEntryVisitor.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Managed/MSIL/CefPdfPrintCallback.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Managed/MSIL/CefPrintHandler.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Managed/MSIL/CefReadHandler.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Managed/MSIL/CefRegisterCDMCallback.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Managed/MSIL/CefRenderHandler.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Managed/MSIL/CefRenderProcessHandler.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Managed/MSIL/CefRequestContextHandler.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Managed/MSIL/CefRequestHandler.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Managed/MSIL/CefResolveCallback.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Managed/MSIL/CefResourceBundleHandler.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Managed/MSIL/CefResourceHandler.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Managed/MSIL/CefResourceRequestHandler.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Managed/MSIL/CefResponseFilter.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Managed/MSIL/CefRunFileDialogCallback.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Managed/MSIL/CefSchemeHandlerFactory.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Managed/MSIL/CefServerHandler.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Managed/MSIL/CefSetCookieCallback.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Managed/MSIL/CefStringVisitor.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Managed/MSIL/CefUrlRequestClient.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Managed/MSIL/CefV8Accessor.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Managed/MSIL/CefV8ArrayBufferReleaseCallback.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Managed/MSIL/CefV8Handler.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Managed/MSIL/CefV8Interceptor.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Managed/MSIL/CefWebPluginInfoVisitor.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Managed/MSIL/CefWebPluginUnstableCallback.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Managed/MSIL/CefWriteHandler.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_accessibility_handler_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_app_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_audio_handler_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_audio_parameters_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_auth_callback_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_base_ref_counted_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_base_scoped_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_before_download_callback_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_binary_value_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_box_layout_settings_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_browser_host_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_browser_process_handler_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_browser_settings_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_browser_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_callback_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_client_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_command_line_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_completion_callback_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_composition_underline_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_context_menu_handler_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_context_menu_params_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_cookie_access_filter_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_cookie_manager_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_cookie_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_cookie_visitor_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_cursor_info_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_delete_cookies_callback_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_dev_tools_message_observer_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_dialog_handler_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_dictionary_value_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_display_handler_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_domdocument_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_domnode_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_domvisitor_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_download_handler_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_download_image_callback_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_download_item_callback_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_download_item_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_draggable_region_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_drag_data_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_drag_handler_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_end_tracing_callback_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_extension_handler_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_extension_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_file_dialog_callback_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_find_handler_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_focus_handler_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_frame_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_get_extension_resource_callback_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_image_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_insets_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_jsdialog_callback_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_jsdialog_handler_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_keyboard_handler_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_key_event_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_life_span_handler_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_list_value_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_load_handler_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_media_observer_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_media_router_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_media_route_create_callback_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_media_route_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_media_sink_device_info_callback_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_media_sink_device_info_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_media_sink_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_media_source_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_menu_model_delegate_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_menu_model_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_mouse_event_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_navigation_entry_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_navigation_entry_visitor_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_pdf_print_callback_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_pdf_print_settings_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_point_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_popup_features_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_post_data_element_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_post_data_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_print_dialog_callback_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_print_handler_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_print_job_callback_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_print_settings_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_process_message_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_range_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_read_handler_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_rect_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_register_cdm_callback_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_registration_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_render_handler_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_render_process_handler_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_request_callback_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_request_context_handler_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_request_context_settings_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_request_context_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_request_handler_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_request_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_resolve_callback_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_resource_bundle_handler_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_resource_bundle_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_resource_handler_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_resource_read_callback_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_resource_request_handler_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_resource_skip_callback_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_response_filter_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_response_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_run_context_menu_callback_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_run_file_dialog_callback_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_scheme_handler_factory_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_scheme_registrar_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_screen_info_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_select_client_certificate_callback_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_server_handler_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_server_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_settings_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_set_cookie_callback_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_size_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_sslinfo_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_sslstatus_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_stream_reader_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_stream_writer_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_string_utf16_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_string_utf8_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_string_visitor_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_string_wide_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_task_runner_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_task_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_thread_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_time_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_touch_event_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_urlparts_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_urlrequest_client_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_urlrequest_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_v8accessor_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_v8array_buffer_release_callback_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_v8context_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_v8exception_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_v8handler_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_v8interceptor_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_v8stack_frame_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_v8stack_trace_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_v8value_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_value_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_waitable_event_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_web_plugin_info_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_web_plugin_info_visitor_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_web_plugin_unstable_callback_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_write_handler_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_x509certificate_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_x509cert_principal_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_xml_reader_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Generated/Native/MSIL/cef_zip_reader_t.il" "/Users/mesign/Downloads/SDApp/CefNet/Internal/MSIL/CefAppGlue.CefRenderProcessHandlerGlue.il" "/Users/mesign/Downloads/SDApp/CefNet/Internal/MSIL/WebViewGlue.CefAudioHandlerGlue.il" "/Users/mesign/Downloads/SDApp/CefNet/Internal/MSIL/WebViewGlue.CefCookieAccessFilterGlue.il" "/Users/mesign/Downloads/SDApp/CefNet/Internal/MSIL/WebViewGlue.CefDisplayHandlerGlue.il" "/Users/mesign/Downloads/SDApp/CefNet/Internal/MSIL/WebViewGlue.CefDownloadHandlerGlue.il" "/Users/mesign/Downloads/SDApp/CefNet/Internal/MSIL/WebViewGlue.CefFocusHandlerGlue.il" "/Users/mesign/Downloads/SDApp/CefNet/Internal/MSIL/WebViewGlue.CefJSDialogHandlerGlue.il" "/Users/mesign/Downloads/SDApp/CefNet/Internal/MSIL/WebViewGlue.CefKeyboardHandlerGlue.il" "/Users/mesign/Downloads/SDApp/CefNet/Internal/MSIL/WebViewGlue.CefRenderHandlerGlue.il" "/Users/mesign/Downloads/SDApp/CefNet/Internal/MSIL/WebViewGlue.CefResourceRequestHandlerGlue.il" "/Users/mesign/Downloads/SDApp/CefNet/UtilExtensions.il"”已退出，代码为 1。 (MSB3073) (CefNet)

The solution I came up with was to delete the following 2 lines from the project file and Visual Studio would compile, but the build-OSx-app.sh installation would crash unexpectedly. I don't think I've found the real reason, so I'm sending it out to see if anyone knows the problem? thank you.The effect I want to achieve now is to debug a CEF project with Visual Studio under MAC OS.

![image](https://user-images.githubusercontent.com/7692353/101716516-62363a00-3ad8-11eb-8812-6d8c6f32a9bb.png)

![image](https://user-images.githubusercontent.com/7692353/101716560-7aa65480-3ad8-11eb-9805-87dd16fe5d58.png)

**Comment by vmas** [comment]
Try to replace
`<ILAsmExe>$(FrameworkPath)\ilasm.exe</ILAsmExe>`
wih
`<ILAsmExe Condition="'$(OS)' == 'Windows_NT'">$(FrameworkPath)\ilasm.exe</ILAsmExe>`

**Comment by wuzlai** [comment]
> Try to replace
> `<ILAsmExe>$(FrameworkPath)\ilasm.exe</ILAsmExe>`
> wih
> `<ILAsmExe Condition="'$(OS)' == 'Windows_NT'">$(FrameworkPath)\ilasm.exe</ILAsmExe>`

Thank you for your prompt reply. I just tried your method. An exception was reported incorrectly.Do I need to install any extensions under MacOS

![image](https://user-images.githubusercontent.com/7692353/101737297-a2f57980-3aff-11eb-9a15-fc09648efe3c.png)

**Comment by vmas** [comment]
It looks like your source is missing this patch: b04dc83

**Comment by wuzlai** [comment]
> It looks like your source is missing this patch: [b04dc83](https://github.com/CefNet/CefNet/commit/b04dc83e4296c487ec9ebf4d42c198ef56b9a154)

thank you I checked these later additions, and I do have them.

![image](https://user-images.githubusercontent.com/7692353/101739859-18af1480-3b03-11eb-8623-d99f5b952882.png)
![image](https://user-images.githubusercontent.com/7692353/101739913-29f82100-3b03-11eb-9e5c-77e08114679c.png)
I can't seem to find the reason for it. I'm actually doing this just to debug the program under macOS. If you have other methods, can you tell me?

**Comment by vmas** [comment]
It is possible that mono ildasm is generating the wrong code. Try to add the `Condition="'$(OS)' == 'Windows_NT'"` for the ILDasmExe.

**Comment by wuzlai** [comment]
> It is possible that mono ildasm is generating the wrong code. Try to add the `Condition="'$(OS)' == 'Windows_NT'"` for the ILDasmExe.

I made 2 modifications. I tried to modify only one, and both of them were exceptions.
Below are the traces of the 2 modifications I made. I'm a little lost...

![image](https://user-images.githubusercontent.com/7692353/101748866-0aafc280-3b08-11eb-8634-9dbe39e2e366.png)
![image](https://user-images.githubusercontent.com/7692353/101748923-18654800-3b08-11eb-98c7-d5314f3aa6e6.png)

![image](https://user-images.githubusercontent.com/7692353/101749062-45195f80-3b08-11eb-81fd-f4c912f69b9d.png)

**Comment by wuzlai** [comment]
> > It is possible that mono ildasm is generating the wrong code. Try to add the `Condition="'$(OS)' == 'Windows_NT'"` for the ILDasmExe.
> 
> I made 2 modifications. I tried to modify only one, and both of them were exceptions.
> Below are the traces of the 2 modifications I made. I'm a little lost...
> 
> ![image](https://user-images.githubusercontent.com/7692353/101748866-0aafc280-3b08-11eb-8634-9dbe39e2e366.png)
> ![image](https://user-images.githubusercontent.com/7692353/101748923-18654800-3b08-11eb-98c7-d5314f3aa6e6.png)
> 
> ![image](https://user-images.githubusercontent.com/7692353/101749062-45195f80-3b08-11eb-81fd-f4c912f69b9d.png)

There is no problem for me to publish directly with dotnet. Are there any other Settings in Visual Studio

**Comment by vmas** [comment]
Looks like Visual Studio's MSBuild can't find the `dotnet` tool.
