### ISSUE TITLE
window.open in AvaloniaApp 

### ISSUE THREAD

**Issue by zhangjacob123** [CefNet/CefNet#4]
I have a website , html include "window.open" button,

When click this button to pops up new page, the current tab is unresponsive or program auto closed.

**Comment by vmas** [comment]
A potential workaround: --disable-gpu-compositing

**Comment by vmas** [comment]
https://bitbucket.org/chromiumembedded/cef/issues/2894/cef-80-crash-on-windowopen-in-osr-mode

**Comment by zhangjacob123** [comment]
I have add  commandLine.AppendSwitch("disable-gpu-compositing"); in CefAppImpl.cs , still same issue.

**Comment by vmas** [comment]
What CEF-version you using? On what operating system?

**Comment by zhangjacob123** [comment]
Cef-version :cef_binary_80.0.4+g74f7b0c+chromium-80.0.3987.122_windows64_minimal.tar and cef_binary_80.0.4+g74f7b0c+chromium-80.0.3987.122_linuxarm_minimal.tar  
OS: Win10 64 and Raspbian

**Comment by zhangjacob123** [comment]
Add my Code
I at AvaloniaApp add new page  Window1.xaml
Xaml 
//// as blow  xaml
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" 
         xmlns:cefnet="clr-namespace:CefNet.Avalonia;assembly=CefNet.Avalonia"
        x:Class="AvaloniaApp.Window1"
        Title="Window1">
  
  <Viewbox >
    <Grid Width="1920" Height="1080">
      <Grid.RowDefinitions >
        <RowDefinition Height="30"></RowDefinition>
        <RowDefinition Height="*" ></RowDefinition>
        <RowDefinition Height="20"></RowDefinition>
      </Grid.RowDefinitions>
      <Border Grid.Row="0"   Background="#FF000000" Height="30" >
        <DockPanel >
          <Image       Width="62" DockPanel.Dock="Left"    />
          <TextBlock ></TextBlock>
          <DockPanel DockPanel.Dock="Right">

          </DockPanel>
        </DockPanel>
      </Border>


      <Border  x:Name="abc" Grid.Column="0"   Grid.Row="1"      BorderThickness="15,15,15,15"    >

         
      </Border>

    </Grid>
   
  </Viewbox>
</Window>

**Comment by vmas** [comment]
Fixed in dae14bf and CEF 80.0.7.
