### ISSUE TITLE
How to use CefNet with visual studio?

### ISSUE THREAD

**Issue by crushglass** [CefNet/CefNet#40]
I was create a avalonia project and downloaded CefNet with nuget in visual studio. When I tried to run the project, I got an error as following.

System.DllNotFoundException
  HResult=0x80131524
  Message=Unable to load DLL 'libcef' or one of its dependencies: ...... (0x8007007E)
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>

**Comment by vmas** [comment]
You need to download a compatible version of [CEF](https://cef-builds.spotifycdn.com/index.html) and specify the path to it. The major and minor versions of CEF and CefNet must match.
