### ISSUE TITLE
Crash report on MacOS when closing app

### ISSUE THREAD

**Issue by Takoooooo** [CefNet/CefNet#41]
Every time I close the sample app on macOS I get a crash report. Maybe I miss something?
![image](https://user-images.githubusercontent.com/53405089/102497769-bbc2d980-4081-11eb-8efc-7c6faea1b337.png)
If you need a full report I will give it to you. Also i have a lot of questions about running CefNet on mac. I cant make it work in debug\release mode,every time i get DirectoryNotFoundeEx,etc. Is it at least possible to run app which uses this library in debug mode?

**Comment by Takoooooo** [comment]
macOS Catalina 10.15.5

**Comment by vmas** [comment]
I got this crash sometimes too.

CEF requires a specific [application layout](https://bitbucket.org/chromiumembedded/cef/issues/2737). It is hardly possible to run the application in debug mode in the standard way.

These links can help you:
https://github.com/Microsoft/MIEngine/wiki/Offroad-Debugging-of-.NET-Core-on-Linux---OSX-from-Visual-Studio
https://github.com/dotnet/coreclr/blob/master/Documentation/building/debugging-instructions.md
https://github.com/dotnet/diagnostics/blob/master/documentation/sos.md

**Comment by vmas** [comment]
Fixed in 2931f13
