### ISSUE TITLE
The web rich text editor built with cefnet.avalonia cannot input Chinese under Linux, only English characters

### ISSUE THREAD

**Issue by wuzlai** [CefNet/CefNet#42]
The web rich text editor built with cefnet.avalonia cannot input Chinese under Linux, only English characters。
Under linux. The textbox can input Chinese normally. But the rich text editor embedded on the basis of cefnet.avalonia cannot input Chinese normally.

I confirm that cefnet.avalonia should be a little problematic for IME support, but I don’t know how to modify cefnet.avalonia so that it conforms to Avalonia’s IME API Chinese input. Excuse you again @vmas , please help me see this problem when you have time. Can you help me modify the source code of this cefnet.avalonia and cefnet project （In my project）? Let him support the input of Chinese.
The download address of my project source code is: https://yunpan.360.cn/surl_yS8VCqMh75d.

In this project, the cef versions I used are cef_binary_84.4.0+g304e015+chromium-84.0.4147.105_linux64.tar.bz2 and cef_binary_84.4.0+g304e015+chromium-84.0.4147.105_windows64.tar.bz2

Because the project runs under the Windows environment by default, if you want to run under Linux, you need to replace the cef package file in the release directory. Here are the specific steps.

 After downloading the information, the "Linux" folder in the compressed package is the linux version of cef package file.Replace all the files in the "Linux " folder to the "Cef " folder in the distribution directory.
![image](https://user-images.githubusercontent.com/7692353/104668328-d5078600-5712-11eb-97ba-98203fbcd201.png)

![image](https://user-images.githubusercontent.com/7692353/104668368-e94b8300-5712-11eb-8047-c0bd4f721942.png)

Publish the project to run under linux, the following is a screenshot of the run。Enter Chinese characters in the edit box inside. It was found that the entry could not be made, and they were all English characters.
![image](https://user-images.githubusercontent.com/7692353/104668408-f8cacc00-5712-11eb-8b75-a34a93085ded.png)

I hope you can take a look when you are free,  thanks. @vmas

**Comment by hopeko** [comment]
你代码过期了，再发一次，我想看看

**Comment by peng007ge** [comment]
I found a solution. The key is TextBoxTextInputMethodClient, rewrite the method in your project.

```
using Avalonia.Controls;
using Avalonia.Input;
using Avalonia.Interactivity;
using CefNet;
using CefNet.Avalonia;
using CefNet.Input;
using CefNet.Internal;
using System;

namespace AvaloniaApp
{
    sealed class CustomWebView : WebView
	{
		public static RoutedEvent<FullscreenModeChangeEventArgs> FullscreenEvent = RoutedEvent.Register<WebView, FullscreenModeChangeEventArgs>("Fullscreen", RoutingStrategies.Bubble);

		public event EventHandler<FullscreenModeChangeEventArgs> Fullscreen
		{
			add { AddHandler(FullscreenEvent, value); }
			remove { RemoveHandler(FullscreenEvent, value); }
		}

		private TextBoxTextInputMethodClient _imClient = new TextBoxTextInputMethodClient();
		static CustomWebView()
		{
			TextInputMethodClientRequestedEvent.AddClassHandler<CustomWebView>((tb, e) =>
			{
				e.Client = tb._imClient;
			});
		}
		public CustomWebView()
		{

		}

		public CustomWebView(WebView opener)
			: base(opener)
		{

		}

		protected override WebViewGlue CreateWebViewGlue()
		{
			return new CustomWebViewGlue(this);
		}



		internal void RaiseFullscreenModeChange(bool fullscreen)
		{
			RaiseCrossThreadEvent(OnFullScreenModeChange, new FullscreenModeChangeEventArgs(this, fullscreen), false);
		}

		private void OnFullScreenModeChange(FullscreenModeChangeEventArgs e)
		{
			RaiseEvent(e);
		}

        protected override void OnTextInput(TextInputEventArgs e)
		{
			foreach (char symbol in e.Text)
            {
                CefEventFlags modifiers = KeycodeConverter.IsShiftRequired(symbol) ? CefEventFlags.ShiftDown : CefEventFlags.None;

				if (symbol >= 0x4e00 && symbol <= 0x9fff)
				{
					var k = new CefKeyEvent();
					k.Type = CefKeyEventType.Char;
					k.WindowsKeyCode = symbol;
					k.Character = symbol;
					k.UnmodifiedCharacter = symbol;
					k.Modifiers = (uint)modifiers;
					k.NativeKeyCode = symbol;
					this.BrowserObject?.Host.SendKeyEvent(k);
				}
				else
				{
					VirtualKeys key = KeycodeConverter.CharacterToVirtualKey(symbol);

					var k = new CefKeyEvent();
					k.Type = CefKeyEventType.Char;
					k.WindowsKeyCode = PlatformInfo.IsLinux ? (int)key : symbol;
					k.Character = symbol;
					k.UnmodifiedCharacter = symbol;
					k.Modifiers = (uint)modifiers;
					k.NativeKeyCode = KeycodeConverter.VirtualKeyToNativeKeyCode(key, modifiers, false);
					this.BrowserObject?.Host.SendKeyEvent(k);
				}
            }
            e.Handled = true;
		}

		protected override void OnPointerPressed(PointerPressedEventArgs e)
		{
			var mousePos = e.GetPosition(this);
			_imClient.SetPosition(mousePos);

			base.OnPointerPressed(e);
		}
	}
}

```
```
using System;
using Avalonia.Controls.Presenters;
using Avalonia.Input.TextInput;
using Avalonia.VisualTree;

namespace Avalonia.Controls
{
    internal class TextBoxTextInputMethodClient : ITextInputMethodClient
    {
        private TextPresenter _presenter;
        private IDisposable _subscription;
        public Rect CursorRectangle => new Rect(new Point(x, y), new Point(x, y + 5)); //_presenter?.GetCursorRectangle() ?? default;
        public event EventHandler CursorRectangleChanged;
        public IVisual TextViewVisual => _presenter;
        public event EventHandler TextViewVisualChanged;
        public bool SupportsPreedit => false;
        public void SetPreeditText(string text) => throw new NotSupportedException();

        public bool SupportsSurroundingText => false;
        public TextInputMethodSurroundingText SurroundingText => throw new NotSupportedException();
        public event EventHandler SurroundingTextChanged;
        public string TextBeforeCursor => null;
        public string TextAfterCursor => null;

        private void OnCaretIndexChanged(int index) => CursorRectangleChanged?.Invoke(this, EventArgs.Empty);
        
        public void SetPresenter(TextPresenter presenter)
        {
            _subscription?.Dispose();
            _subscription = null;
            _presenter = presenter;
            if (_presenter != null)
            {
                _subscription = _presenter.GetObservable(TextPresenter.CaretIndexProperty)
                    .Subscribe(OnCaretIndexChanged);
            }
            TextViewVisualChanged?.Invoke(this, EventArgs.Empty);
            CursorRectangleChanged?.Invoke(this, EventArgs.Empty);
        }

        //设置输入框位置
        private double x, y;
        public void SetPosition(Point pos)
        {
            x = pos.X;
            y = pos.Y;
            CursorRectangleChanged?.Invoke(this, EventArgs.Empty);
        }
    }
}
```

**Comment by wuzlai** [comment]
> I found a solution. The key is TextBoxTextInputMethodClient, rewrite the method in your project.
> 
> ```
> using Avalonia.Controls;
> using Avalonia.Input;
> using Avalonia.Interactivity;
> using CefNet;
> using CefNet.Avalonia;
> using CefNet.Input;
> using CefNet.Internal;
> using System;
> 
> namespace AvaloniaApp
> {
>     sealed class CustomWebView : WebView
> 	{
> 		public static RoutedEvent<FullscreenModeChangeEventArgs> FullscreenEvent = RoutedEvent.Register<WebView, FullscreenModeChangeEventArgs>("Fullscreen", RoutingStrategies.Bubble);
> 
> 		public event EventHandler<FullscreenModeChangeEventArgs> Fullscreen
> 		{
> 			add { AddHandler(FullscreenEvent, value); }
> 			remove { RemoveHandler(FullscreenEvent, value); }
> 		}
> 
> 		private TextBoxTextInputMethodClient _imClient = new TextBoxTextInputMethodClient();
> 		static CustomWebView()
> 		{
> 			TextInputMethodClientRequestedEvent.AddClassHandler<CustomWebView>((tb, e) =>
> 			{
> 				e.Client = tb._imClient;
> 			});
> 		}
> 		public CustomWebView()
> 		{
> 
> 		}
> 
> 		public CustomWebView(WebView opener)
> 			: base(opener)
> 		{
> 
> 		}
> 
> 		protected override WebViewGlue CreateWebViewGlue()
> 		{
> 			return new CustomWebViewGlue(this);
> 		}
> 
> 
> 
> 		internal void RaiseFullscreenModeChange(bool fullscreen)
> 		{
> 			RaiseCrossThreadEvent(OnFullScreenModeChange, new FullscreenModeChangeEventArgs(this, fullscreen), false);
> 		}
> 
> 		private void OnFullScreenModeChange(FullscreenModeChangeEventArgs e)
> 		{
> 			RaiseEvent(e);
> 		}
> 
>         protected override void OnTextInput(TextInputEventArgs e)
> 		{
> 			foreach (char symbol in e.Text)
>             {
>                 CefEventFlags modifiers = KeycodeConverter.IsShiftRequired(symbol) ? CefEventFlags.ShiftDown : CefEventFlags.None;
> 
> 				if (symbol >= 0x4e00 && symbol <= 0x9fff)
> 				{
> 					var k = new CefKeyEvent();
> 					k.Type = CefKeyEventType.Char;
> 					k.WindowsKeyCode = symbol;
> 					k.Character = symbol;
> 					k.UnmodifiedCharacter = symbol;
> 					k.Modifiers = (uint)modifiers;
> 					k.NativeKeyCode = symbol;
> 					this.BrowserObject?.Host.SendKeyEvent(k);
> 				}
> 				else
> 				{
> 					VirtualKeys key = KeycodeConverter.CharacterToVirtualKey(symbol);
> 
> 					var k = new CefKeyEvent();
> 					k.Type = CefKeyEventType.Char;
> 					k.WindowsKeyCode = PlatformInfo.IsLinux ? (int)key : symbol;
> 					k.Character = symbol;
> 					k.UnmodifiedCharacter = symbol;
> 					k.Modifiers = (uint)modifiers;
> 					k.NativeKeyCode = KeycodeConverter.VirtualKeyToNativeKeyCode(key, modifiers, false);
> 					this.BrowserObject?.Host.SendKeyEvent(k);
> 				}
>             }
>             e.Handled = true;
> 		}
> 
> 		protected override void OnPointerPressed(PointerPressedEventArgs e)
> 		{
> 			var mousePos = e.GetPosition(this);
> 			_imClient.SetPosition(mousePos);
> 
> 			base.OnPointerPressed(e);
> 		}
> 	}
> }
> ```
> 
> ```
> using System;
> using Avalonia.Controls.Presenters;
> using Avalonia.Input.TextInput;
> using Avalonia.VisualTree;
> 
> namespace Avalonia.Controls
> {
>     internal class TextBoxTextInputMethodClient : ITextInputMethodClient
>     {
>         private TextPresenter _presenter;
>         private IDisposable _subscription;
>         public Rect CursorRectangle => new Rect(new Point(x, y), new Point(x, y + 5)); //_presenter?.GetCursorRectangle() ?? default;
>         public event EventHandler CursorRectangleChanged;
>         public IVisual TextViewVisual => _presenter;
>         public event EventHandler TextViewVisualChanged;
>         public bool SupportsPreedit => false;
>         public void SetPreeditText(string text) => throw new NotSupportedException();
> 
>         public bool SupportsSurroundingText => false;
>         public TextInputMethodSurroundingText SurroundingText => throw new NotSupportedException();
>         public event EventHandler SurroundingTextChanged;
>         public string TextBeforeCursor => null;
>         public string TextAfterCursor => null;
> 
>         private void OnCaretIndexChanged(int index) => CursorRectangleChanged?.Invoke(this, EventArgs.Empty);
>         
>         public void SetPresenter(TextPresenter presenter)
>         {
>             _subscription?.Dispose();
>             _subscription = null;
>             _presenter = presenter;
>             if (_presenter != null)
>             {
>                 _subscription = _presenter.GetObservable(TextPresenter.CaretIndexProperty)
>                     .Subscribe(OnCaretIndexChanged);
>             }
>             TextViewVisualChanged?.Invoke(this, EventArgs.Empty);
>             CursorRectangleChanged?.Invoke(this, EventArgs.Empty);
>         }
> 
>         //设置输入框位置
>         private double x, y;
>         public void SetPosition(Point pos)
>         {
>             x = pos.X;
>             y = pos.Y;
>             CursorRectangleChanged?.Invoke(this, EventArgs.Empty);
>         }
>     }
> }
> ```

Thank you very much for your reply. With the communication , the latest version of Avalonia has supported Chinese input under Linux. I will test the method you provided later

**Comment by wuzlai** [comment]
> 你代码过期了，再发一次，我想看看

时间有点久了，你参考下这个https://github.com/CefNet/CefNet/files/5063718/cef-84_4-example.zip。
另外最新版本的Avalonia已经支持linux下的中文输入。
