### ISSUE TITLE
Multiple CefBrowser Instances

### ISSUE THREAD

**Issue by Vittitow** [CefNet/CefNet#5]
Does this library support running multiple CefBrowser instances in the same application? If it does, I can't seem to figure it out. Would you be able to provide an example?

I see the CefNetApplication can only be initialized once which makes me think it's only one CefBrowser per application.

Thanks!

**Comment by vmas** [comment]
The CefNetApplication implements [the CefApp interface](https://magpcss.org/ceforum/apidocs3/projects/(default)/CefApp.html) and some handlers, and loads the CEF library. The CEF library can be loaded into the process only once. Access to the [CefBrowser](https://magpcss.org/ceforum/apidocs3/projects/(default)/CefBrowser.html) interface is implemented in the WebView and WindowlessWebView classes. Each WebView instance is a wrapper around the CefBrowser instance. Browsers are implemented as tabs in the samples.

**Comment by Vittitow** [comment]
Maybe I can restate my use case better... It would appear that there is only a single ChromiumWebBrowser process running as the OnBeforeCommandLineProcessing is only invoked once. What I need to do is have multiple chromium browser instances using independent user data directories displayed in the same UI. Would this be possible?

Thanks again!

**Comment by vmas** [comment]
You should [create each browser with own request context](https://github.com/CefNet/CefNet/blob/a39ad3ffe74a15301b4e2b22846b7958682bca78/WinFormsCoreApp/MainForm.cs#L153) (CefRequestContext). The CEF API allows you to specify a cache path via CefRequestContextSettings when creating a request context.

If you want to add something to the command line when starting a child process, then you need to override the CefNetApplication.OnBeforeChildProcessLaunch method or subscribe to the CefNetApplication.BeforeChildProcessLaunch event.
