### ISSUE TITLE
WebView.Initialized doesn't fire

### ISSUE THREAD

**Issue by hopeko** [CefNet/CefNet#51]
Just like what the title says. WebView.Initialized doesn't fire after it initialized.

**Comment by vmas** [comment]
I cannot reproduce. WebView.Initialized is the lifecycle event of the Avalonia's StyledElement. Perhaps you are expecting something different.

**Comment by hopeko** [comment]
I just create a new AvaloniaMVVM project based on .Net 5.0. Then
1. Install CefNet.Avalonia (88.1.21022.1657)
2. Handle CEF Initialize code (Code from AvaloniaApp)
3. Add WebView to axaml
4. Add WebView.Initialized event
5. Start project

Version
VS: Microsoft Visual Studio Community 2019 Version 16.8.4
Packages
Avalonia 0.10.0
Avalonia.Desktop 0.10.0
Avalonia.Diagnostics 0.10.0
Avalonia.ReactiveUI 0.10.0
CefNet.Avalonia 88.1.21022.1657

MainWindow.axaml
```cs
...
        xmlns:cefnet="clr-namespace:CefNet.Avalonia;assembly=CefNet.Avalonia"
...
  <cefnet:WebView Name="webView" />
...
```
MainWindow.axaml.cs
```cs
    public class MainWindow : Window
    {
        private WebView webView;

        public MainWindow()
        {
            InitializeComponent();
#if DEBUG
            this.AttachDevTools();
#endif
        }

        private void InitializeComponent()
        {
            AvaloniaXamlLoader.Load(this);
            webView = this.FindControl<WebView>(nameof(webView));
            webView.Initialized += WebView_Initialized;
        }

        private void WebView_Initialized(object? sender, System.EventArgs e)
        {
            Debug.WriteLine("WebView_Initialized");
        }
    }
```

Shouldn't `Debug.WriteLine("WebView_Initialized")` fire?

**Comment by vmas** [comment]
You are subscribing to WebView.Initialized too late. Use `<cefnet:WebView Name="webView" Initialized="WebView_Initialized" />` instead.

**Comment by hopeko** [comment]
Oh, I see. Thanks.
