### ISSUE TITLE
Test project crashes on loading flash

### ISSUE THREAD

**Issue by h3xb0y** [CefNet/CefNet#58]
Mac OS X 10.14.6
CefNet/CefNet.Avalonia 87.1.20333.1751

im embedding flash player via command line args

commandLine.AppendSwitchWithValue("enable-system-flash", "1");
commandLine.AppendSwitchWithValue("allow-outdated-plugins", "1");
commandLine.AppendSwitchWithValue("ppapi-flash-path", "/Library/Internet Plug-Ins/PepperFlashPlayer/PepperFlashPlayer.plugin");

but on loading my page with flash content AvaloniaApp crashes
![Screen Shot 2021-02-26 at 7 04 17 PM](https://user-images.githubusercontent.com/24976002/109331542-a1696100-7865-11eb-8707-5a8778297fa1.png)

**Comment by h3xb0y** [comment]
windows error in stacktrace
[0226/224712.670:ERROR:ppapi_thread.cc(309)] Failed to load Pepper module from pepperflashplayer.dll (error: 126)

**Comment by h3xb0y** [comment]
stacktrace in windows build
[0226/225302.560:ERROR:ppapi_thread.cc(309)] Failed to load Pepper module from C:\Users\User\My\Custom\Path\pepflashplayer.dll (error: 126)

**Comment by vmas** [comment]
Have you tried with cefclient.exe? Adobe Flash is no longer supported as per the [Chromium Flash Roadmap](https://www.chromium.org/flash-roadmap#TOC-Flash-Player-blocked-as-out-of-date-Target:-All-Chrome-versions---Jan-2021-).

**Comment by h3xb0y** [comment]
>Adobe Flash is no longer supported as per the Chromium Flash Roadmap.

yep, therefore im trying embed flashplayer on previous cefnet version
![image](https://user-images.githubusercontent.com/24976002/109354530-9d017000-7886-11eb-852e-1de52803e329.png)

**Comment by h3xb0y** [comment]
i know, this is not actual for the last version. but maybe u have some ideas how i can fix this? @vmas

**Comment by vmas** [comment]
Я никогда не пробовал запускать Flash-плагин c CEF. Скачайте архив CEF с тестовой программой. Если в cefclient.exe он работает, то может быть и тут получится. В последних версиях CEF 87.1.13+, или даже в 87.1.12, возможно он выпилен частично, поэтому проверять желательно на 87.1.6 или 87.1.11. Также может быть версия DLL-ки не подходит.

**Comment by h3xb0y** [comment]
>о может быть и тут получится. В последних версиях CEF 87.1.13+, или даже в 87.1.12, возможно он выпилен частично, поэтому проверять желательно на 87.1.6 или 87.1.11. 

проверял еще на 83.4, та же трабла
>Также может быть версия DLL-ки не подходит.

dll плагина? не, с плагином все в порядке.

**Comment by vmas** [comment]
Проверил на AvaloniApp (x86) 87 ветки с CEF 87.1.14 (windows32) и pepflashplayer32_32_0_0_371.dll - флеш запустился без проблем.

**Comment by h3xb0y** [comment]
32_0_0_371 - это версия со вшитой тайм бомбой, сейчас на этой версии нельзя смотреть флешконтент, в теории
я тоже пробую в 87 ветке с CEF 87.1.14(x64)
[0228/152138.004:ERROR:ppapi_thread.cc(309)] Failed to load Pepper module from pepflashplayer.dll (error: 126)
[0228/152439.442:ERROR:ppapi_thread.cc(309)] Failed to load Pepper module from pepflashplayer.dll (error: 193)

первая ошибка - когда разрядность плагина соответствует разрядности приложения
вторая - наборот

можете, пожалуйста, проверить у себя работоспособность с этими версиями плагинами? спасибо!
[check_fp_project.zip](https://github.com/CefNet/CefNet/files/6056863/check_fp_project.zip)

**Comment by h3xb0y** [comment]
хмм, на винде проблема решилась тем что я добавил CefSettings.CachePath

**Comment by vmas** [comment]
С этими версиями не понятно. Ошибок в логе не вижу, но при попытке запуска плагина отображается пустая белая страница. С 32_0_0_371 видна кнопка и надпись. При проверке другой флешки плагины работают.
PS: тайм бомба, кажется, в 32.0.0.465.

**Comment by h3xb0y** [comment]
>PS: тайм бомба, кажется, в 32.0.0.465.

да, сори за дизинформацию

кажется понял в чем проблема
проблема в кеше и в версии плагина. это две версии плагина в архиве дебажные и проект в архиве тоже дебажный, и видимо для работы с дебажными флешками дебажному плагину нужно проинициализировать настройки в кеше(Cache -> Pepper Data) иначе он не сможет воспроизвести флеш контент. с релизными плагинами и флешками эта проблема не актуальна
спасибо и сори за беспокойство)

**Comment by h3xb0y** [comment]
>хмм, на винде проблема решилась тем что я добавил CefSettings.CachePath

и на macos тоже решилась
