### ISSUE TITLE
Cefnet 'Failed to create browser instance.'

### ISSUE THREAD

**Issue by HoangNguyenABC** [CefNet/CefNet#60]
Hi all.

My issue is 'Failed to create browser instance.'
This is init code
![image](https://user-images.githubusercontent.com/33251125/115186388-d084ac00-a10b-11eb-90cc-0828555aaa0d.png)
and xaml code
![image](https://user-images.githubusercontent.com/33251125/115186506-0e81d000-a10c-11eb-834e-0d7819ac12e1.png)

i'm using cefnet.avalonia version 88.1.21022.1657. After im try using almost version cef about supported ver 88.1.* but i'm always recieve this mes :Failed to create browser instance". We have some remaining solutions right now? :)

**Comment by vmas** [comment]
Why are you using InvokeAsync to initialize the CefNetApplication? I think the app hasn't been initialized yet at the time of browser creation.

**Comment by HoangNguyenABC** [comment]
Because when i'm not using InvokeAsync i'm receive 
![image](https://user-images.githubusercontent.com/33251125/115189488-ba2d1f00-a110-11eb-8dae-07d1a28890f4.png)

**Comment by vmas** [comment]
Add the STAThreadAttribute to the Main().

**Comment by HoangNguyenABC** [comment]
It's not work too Bro. After call Initialize(), application exit with mes "Access violation". I'm still find the ways.

**Comment by vmas** [comment]
The path to the resources (* .pak, icudtl.dat) is probably wrong. See debug.log.

**Comment by HoangNguyenABC** [comment]
It's worked Bro, so much thank you. I'm missing copy  icu file to Release cef folder.
