### ISSUE TITLE
Webview Tab window is lagging

### ISSUE THREAD

**Issue by Pulse-Git** [CefNet/CefNet#70]
Hello
Ive noticed when im running the AvaloniaApp is quite lagging in scrolling and animation,

if the open the same page in an popup (menuitem) File>Tests>"Open unhandled..."

is there any reason why the popup is not lagging and the same page in an tab is lagging?

**Comment by Pulse-Git** [comment]
@vmas any way to use the native window as an control?

**Comment by vmas** [comment]
Try to embed it using NativeControlHost. I have not tried it.

**Comment by Pulse-Git** [comment]
Sadly im new to Avalonia, any point to start?

**Comment by vmas** [comment]
You can get the top-level window handle from `CefBrowser.Host.WindowHandle`, at least on Windows. However, I don't think embedding a top-level window is the right way to go. Pay attention to [the OutSystems WebView project](https://github.com/OutSystems/WebView), if I'm not mistaken, it supports embedding a native CefBowser.

**Comment by Pulse-Git** [comment]
@vmas any way to get this working on Linux? OutSystem Webview has sadly no Linux support.

The NativeControlHost, is also empty, maybe im doing something wrong

`    public class CEFNativeControl : NativeControlHost
    {

        public IPlatformHandle CreateLinux(IPlatformHandle parent)
        {
            return new PlatformHandle(MainWindow.webView.BrowserObject.Host.WindowHandle, "HWND");
        }

        void DestroyLinux(IPlatformHandle handle)
        {
            base.DestroyNativeControlCore(handle);
        }

        protected override IPlatformHandle CreateNativeControlCore(IPlatformHandle parent)
        {
            return CreateLinux(parent);
        }

        protected override void DestroyNativeControlCore(IPlatformHandle control)
        {
                DestroyLinux(control);
        }

    }`

**Comment by vmas** [comment]
Sorry, I don't know if embedding a top-level window is possible on Linux.
