### ISSUE TITLE
Blank page when navigation fails

### ISSUE THREAD

**Issue by Bil97** [CefNet/CefNet#74]
![Screenshot (12)](https://user-images.githubusercontent.com/36190575/134808486-2ff46cfe-8d35-4234-ad9c-373f1ff0ed95.png)
When the browser fails to navigate to the given url, It display a blank page with no error message. How do i get the error message or how do i alert a user that loading failed. I cant get any method do do that.
In CefSharp I could use the LoadError event but CefSharp is not crossplatform.

Also how do I get the current url loaded by the browser?.

In CefSharp I could use the _browser.Address but CefSharp is not crossplatform.

Thanks in advance

**Comment by vmas** [comment]
> Also how do I get the current url loaded by the browser?.

`WebView.GetMainFrame().Url`

**Comment by vmas** [comment]
The LoadError event has been added since CefNet 94.3.
