### ISSUE TITLE
What's the point of "AvoidXY" functions?

### ISSUE THREAD

**Issue by lumip** [CefNet/CefNet#80]
I've been looking into getting download handling to work but I am very puzzled by the `AvoidXY` that are found everywhere in the code base (in particular `CefDownloadHandlerPrivate::AvoidOnBeforeDownload()` and `::AvoidOnDownloadUpdated` (and the same for `WebViewGlue`)).
They all seem to be auto-generated and compare some function pointers, but I don't really understand what they are for and why they are needed. As it currently stands, they seem to be the only thing that really prevent users from adding download handlers, so could someone explain what these are for?

**Comment by vmas** [comment]
`ABCHandlerPrivate::AvoidXY()`, if implemented, returns `true` if function `XY()` was not overloaded. If `AvoidXY` returns `true`, then .NET-wrappers for CEF-objects passed as arguments to the static handler function are not created and `ABCHandler::XY()` is not called. In this case, the static handler returns a default value to the calling native code.

**Comment by lumip** [comment]
Wouldn't it be easier to just have the non-overloaded function return that default value instead of resorting to all that intransparent reflection magic?
I'm still not entirely sure I get this, please help me out a bit more:

With static handler functions, do you mean the `XYImpl()` in `Generated/Managed/Types/CefABC.cs`? In the case of the `CefDownloadHandler::OnBeforeDownload`, that seems to get checked in a lot of other places as well (e.g. in `WebViewGlue::CreateOrDestroyDownloadGlue`, where it removes the `DownloadGlue` instance that was previously created in the constructor of that class).

Where would `XY()` need to be overloaded/overridden exactly? For example, the IL file for `AvoidOnBeforeDownload` compares
```
ldvirtftn instance void CefNet.CefDownloadHandler::OnBeforeDownload(class CefNet.CefBrowser, class CefNet.CefDownloadItem, string, class CefNet.CefBeforeDownloadCallback)
ldftn instance void CefNet.CefDownloadHandler::OnBeforeDownload(class CefNet.CefBrowser, class CefNet.CefDownloadItem, string, class CefNet.CefBeforeDownloadCallback)
```
which is the root level class of any possible inheritance. There is an overriding declaration in `CefDownloadHandlerGlue`, which is not checked. So what qualifies as "function `XY()` was not overloaded"?

**Comment by vmas** [comment]
`CefDownloadHandlerGlue` is a proxy that invokes handlers in `WebViewGlue`. `CefDownloadHandlerGlue` is instantiated only if there are overloaded handlers in `WebViewGlue` (this is checked in `WebViewGlue::CreateOrDestroyDownloadGlue`). The methods defined in the Generated/Managed/MSIL/CefDownloadHandler.il file are not called in this case. Instead, overrides of the functions `WebViewGlue::OnBeforeDownload` and `WebViewGlue::OnDownloadUpdated` are checked (Internal/MSIL/WebViewGlue.CefDownloadHandlerGlue.il).

You need to override the functions `WebViewGlue::OnBeforeDownload` and` WebViewGlue::OnDownloadUpdated`.

**Comment by lumip** [comment]
I have tried providing an implementation of `OnBeforeDownload` instead of the default empty one in `WebViewGlue` but that did not work.
