### ISSUE TITLE
How to implement IDownloadHandler in CefNet

### ISSUE THREAD

**Issue by halgari** [CefNet/CefNet#82]
I've recently ported my code from CefSharp to CefNet, and for the most part I much prefer CefNet's interfaces. One issue though, I can't find the best way to hook into Cef's download routines via the `IDownloadHandler`. Can someone give me a hint as to where I'd need to go to do this? I'm using Avalonia so I'm using the default `WebVew` and the CefClient it creates.

**Comment by vmas** [comment]
The downoad events can be handled now by overriding functions `AvaloniaWebViewGlue::OnBeforeDownload` and `AvaloniaWebViewGlue::OnDownloadUpdated` (in CustomWebViewGlue.cs).

**Comment by halgari** [comment]
That'll do it! Thank you so much for the help.
