### ISSUE TITLE
CefGen doesn't work on windows

### ISSUE THREAD

**Issue by Braidon** [CefNet/CefNet#90]
Parser cannot find <stdint.h> header if run at windows 10.
As far as I know, there is no more "include" path at environment variables, and alternative to hardcode path is vswhere

**Comment by vmas** [comment]
I can't reproduce the issue from my side.

**Comment by Braidon** [comment]
I cloned repository, and made steps described at readme (dev).

Next, open the CefGenSolution, build and run.
![изображение](https://user-images.githubusercontent.com/10419475/167893974-f600cec5-50a1-4f46-82e6-5c0a9ab04a78.png)

It seems utility cannot find folder with std headers. I have added it to paths.
![изображение](https://user-images.githubusercontent.com/10419475/167894937-656429c7-9623-45b3-aff3-27915558b1ba.png)

As far as I remember, C++ headers/libs paths must be at enviroment variables, but I didn't found it.
At last, running app gives us an exception
![изображение](https://user-images.githubusercontent.com/10419475/167897654-856144b2-9498-4802-8802-958e3537eb90.png)

It seems, header include files you didn't expect and I need to fix it manually.

FYI
Cef.Net - 101.0
CEF - 101.0.15+gca159c5+chromium-101.0.4951.54
Windows 10
VS 2022
Windows SDK/WDK 10.0.22000.1

**Comment by vmas** [comment]
Try adding the path to `options.SystemIncludeFolders`.
